/**
 * databaseTranslator.js
 * Dictionary and helper to translate dynamic English database strings
 * and standard alignment profiles to Russian when selected.
 */

const DB_TRANSLATIONS = {
  // --- Tubulars specific lists (advantages, limitations, applications) ---
  "Controlled yield strength for mild sour service": "Контролируемый предел текучести для слабокислых сред",
  "Good collapse resistance": "Хорошее сопротивление смятию",
  "Not for high H2S concentrations": "Не подходит для высоких концентраций H₂S",
  "Medium pressure limit": "Средний лимит давления",
  "Intermediate casing sections": "Промежуточные секции обсадных колонн",
  "Medium-depth wells": "Скважины средней глубины",
  "Highly ductile": "Высокая пластичность",
  "Very economic choice": "Очень экономичный выбор",
  "Standard global availability": "Стандартная глобальная доступность",
  "Low corrosion resistance in sour gas": "Низкая коррозионная стойкость в кислом газе",
  "Low collapse rating": "Низкое сопротивление смятию",
  "Low-pressure production wells": "Низконапорные эксплуатационные скважины",
  "Water injection/disposal wells": "Нагнетательные/водозаборные скважины",
  "Sour service compatibility (NACE MR0175 compliance)": "Совместимость с кислыми средами (соответствие NACE MR0175)",
  "Good tensile strength": "Хорошая прочность на растяжение",
  "Not suitable for high CO2 with high watercut without inhibition": "Не подходит для высокого содержания CO₂ с высокой обводненностью без ингибирования",
  "Standard production wells with mild H2S": "Стандартные добывающие скважины со слабым содержанием H₂S",
  "Deep completion strings": "Глубокие эксплуатационные колонны",
  "Excellent Sulfide Stress Cracking (SSC) resistance": "Отличное сопротивление сульфидному растрескиванию под напряжением (РКН)",
  "Very high collapse ratings": "Очень высокая стойкость к смятию",
  "Higher cost": "Более высокая стоимость",
  "Susceptible to severe CO2 corrosion in wet gas without inhibitors": "Подвержен сильной углекислотной коррозии во влажном газе без ингибиторов",
  "Severe H2S wells": "Скважины с высоким содержанием H₂S",
  "Deep sour gas completions": "Глубокие газовые скважины с кислыми средами",
  "High-stress production strings": "Высоконагруженные эксплуатационные колонны",
  "Exceptional tensile and burst ratings": "Исключительная прочность на растяжение и внутреннее давление",
  "Suitable for deep vertical wells": "Подходит для глубоких вертикальных скважин",
  "Not resistant to H2S (SSC hazard)": "Неустойчив к H₂S (риск сульфидного растрескивания)",
  "Strict temperature limits under stress": "Строгие температурные ограничения под нагрузкой",
  "Deep sweet gas completions": "Глубокие газовые скважины со сладкими средами",
  "High-pressure wells": "Скважины с высоким давлением (HP)",
  "Maximum yield strength": "Максимальный предел текучести",
  "High collapse resistance for deep reservoirs": "Высокое сопротивление смятию для глубоких коллекторов",
  "No H2S resistance (very brittle in sour environment)": "Нет стойкости к H₂S (хрупкое разрушение в кислой среде)",
  "Deep gas wells": "Глубокие газовые скважины",
  "HPHT reservoir sections": "Интервалы пластов с АВПД и АВТ (HPHT)",
  "Great balance of tensile strength and price": "Отличный баланс прочности на растяжение и цены",
  "Wide availability": "Широкая доступность",
  "High susceptibility to SSC in H2S environments": "Высокая чувствительность к сульфидному растрескиванию в средах H₂S",
  "Intermediate sections in deep wells": "Промежуточные секции глубоких скважин",
  "Production casing in sweet wells": "Эксплуатационные колонны в сладких скважинах",
  "Economic surface protection": "Экономичная защита кондуктора",
  "Ductile and easily welded": "Пластичный и легко свариваемый",
  "Low collapse threshold": "Низкий порог смятия",
  "No acid/H2S resistance": "Отсутствие стойкости к кислотам и H₂S",
  "Surface hole isolation": "Изоляция верхних интервалов",
  "Water aquifer protection": "Защита водоносных горизонтов",
  "High structural bending capacity": "Высокая изгибающая способность конструкции",
  "Cheap, easy to weld/joint": "Дешевый, простой монтаж/сварка",
  "Low burst and collapse rating": "Низкая прочность на разрыв и смятие",
  "Heavy weight per unit length": "Большой вес на единицу длины",
  "Structural casing sections": "Направление (структурная колонна)",
  "Top-hole drilling stabilization": "Стабилизация устья при бурении под направление",
  "Light weight": "Легкий вес",
  "Excellent flexibility in high dogleg severities": "Отличная гибкость в интервалах с высокой интенсивностью искривления",
  "Low torsional limit compared to high grades": "Низкий крутящий момент по сравнению с высокопрочными группами",
  "Slim hole drilling": "Бурение малым диаметром",
  "Coiled tubing and workover operations": "Колтюбинг и ремонтные работы",
  "Balanced tensile-to-weight ratio": "Сбалансированное отношение прочности к весу",
  "Good fatigue resistance": "Хорошая усталостная прочность",
  "Limited sour service compatibility": "Ограниченная совместимость с кислыми средами",
  "Directional drilling": "Направленное бурение",
  "Standard workovers": "Стандартное КРС",
  "High ductility": "Высокая пластичность",
  "Good fatigue life in abrasive wells": "Хороший усталостный ресурс в абразивных скважинах",
  "Lower tensile limit than S135": "Более низкий предел прочности, чем у S135",
  "Intermediate hole section drilling": "Бурение под промежуточную колонну",
  "Medium torque operations": "Операции со средним крутящим моментом",
  "Maximum tensile limit": "Максимальный предел прочности",
  "High torsional capacity": "Высокая крутящая способность",
  "Excellent fatigue limits": "Отличная усталостная прочность",
  "Highly susceptible to sulfide stress cracking in H2S": "Очень высокая чувствительность к сульфидному растрескиванию в H₂S",
  "High cost": "Высокая стоимость",
  "Deep drilling": "Глубокое бурение",
  "Extended reach drilling (ERD)": "Бурение с большим отходом от вертикали (ERD)",
  "High torque operations": "Операции с высоким крутящим моментом",
  "Very high tensile rating": "Очень высокая прочность на растяжение",
  "Lower pressure drop due to large ID": "Низкий перепад давления благодаря большому ВД",
  "Very heavy, requires high capacity rigs": "Очень тяжелый, требует буровых установок большой грузоподъемности",
  "Extremely stiff": "Чрезвычайно жесткий",
  "Extended reach horizontal drilling": "Горизонтальное бурение с большим отходом",
  "Deep marine gas wells": "Глубокие морские газовые скважины",

  // --- Used in equipment ---
  "Intermediate casing strings": "Промежуточные обсадные колонны",
  "Production casing strings": "Эксплуатационные обсадные колонны",
  "Conductor casing": "Направление (кондуктор)",
  "Structural liners": "Структурные хвостовики",
  "Coiled tubing reels": "Барабаны колтюбинга",
  "Workover strings": "Колонны ГТМ / КРС",
  "Drill strings": "Бурильные колонны",
  "High dogleg sections": "Интервалы с высокой интенсивностью искривления",
  "Severe environments": "Агрессивные среды",
  "Deep vertical sections": "Глубокие вертикальные секции",
  "Extended reach sections": "Секции с большим отходом",

  // --- Standard Classification profiles ---
  "API Spec 5CT (High Strength)": "API Spec 5CT (Высокопрочная)",
  "ISO 11960 Group 3": "ISO 11960 Группа 3",
  "High Strength Carbon Steel": "Высокопрочная углеродистая сталь",
  "Sweet Service Only (No H₂S)": "Только для слабокислых сред (без H₂S)",
  "Yield: 110-140 ksi, Temp: Stable": "Текучесть: 110-140 ksi, Стабильная темп.",
  "API Spec 5CT / NACE MR0175": "API Spec 5CT / NACE MR0175",
  "ISO 13680 / ISO 15156 (CRA)": "ISO 13680 / ISO 15156 (CRA)",
  "Corrosion Resistant Alloy (13Cr CRA)": "Коррозионно-стойкий сплав (13Cr CRA)",
  "Sour Service Capable (H₂S + CO₂)": "Подходит для кислых сред (H₂S + CO₂)",
  "Yield: Min 80 ksi, NACE MR0175 Limits Apply": "Текучесть: мин. 80 ksi, лимиты NACE MR0175",
  "API Spec 5CT (Group 2, L80)": "API Spec 5CT (Группа 2, L80)",
  "ISO 11960 Group 2": "ISO 11960 Группа 2",
  "Controlled Hardness Carbon Steel": "Углеродистая сталь контролируемой твердости",
  "Sour Service Capable (H₂S Suitable)": "Подходит для кислых сред (H₂S Suitable)",
  "Yield: 80-95 ksi, Max Hardness 23 HRC": "Текучесть: 80-95 ksi, макс. твердость 23 HRC",
  "API Spec 5CT (Group 4, Q125)": "API Spec 5CT (Группа 4, Q125)",
  "ISO 11960 Group 4": "ISO 11960 Группа 4",
  "Ultra High Strength Carbon Steel": "Ультравысокопрочная углеродистая сталь",
  "Sweet Service (Special H₂S limits)": "Слабокислая среда (спец. лимиты H₂S)",
  "Yield: 125-150 ksi, Critical Design Only": "Текучесть: 125-150 ksi, только ответственные конструкции",
  "ISO 13680 / ISO 15156": "ISO 13680 / ISO 15156",
  "Corrosion Resistant Alloy (CRA)": "Коррозионно-стойкий сплав (CRA)",
  "Sour Service Capable (High CO₂ / Mild H₂S)": "Подходит для кислых сред (высокий CO₂ / слабый H₂S)",
  "Yield: Min 95-110 ksi, Max Temp 180°C": "Текучесть: мин. 95-110 ksi, макс. темп. 180°C",
  "NACE MR0175 / ISO 15156 (CRA)": "NACE MR0175 / ISO 15156 (CRA)",
  "ISO 13680 (High CRA)": "ISO 13680 (Высоколегированный CRA)",
  "Super Corrosion Resistant Alloy (High Al)": "Суперкоррозионностойкий сплав (High Al)",
  "Severe HPHT Sour & High Chloride": "Агрессивный HPHT флюид (кислый и с хлоридами)",
  "Extreme Resistance to Pit & SSC Corrosion": "Экстремальная стойкость к питтингу и сульфидному растрескиванию",
  "API Spec 5CT": "API Spec 5CT",
  "ISO 11960": "ISO 11960",
  "Oilfield Steel Grade": "Промысловый сорт стали",
  "Standard Casing & Tubing Service": "Стандартная эксплуатация обсадных и НКТ колонн",
  "Grade Dependent Limits": "Лимиты зависят от группы прочности",

  // --- Connections / Threads profiles ---
  "API Spec 5B (Standard Thread)": "API Spec 5B (Стандартная резьба)",
  "ISO 11960 (API Threads)": "ISO 11960 (Резьбы API)",
  "Standard API Thread Connection": "Стандартное резьбовое соединение API",
  "Moderate Tension & Low Pressure Service": "Умеренное растяжение и низкое рабочее давление",
  "Grease Dependent Helical Thread Seal": "Герметизация витков за счет резьбовой смазки",
  "API Spec 5B / ISO 13679": "API Spec 5B / ISO 13679",
  "ISO 13679 Connection Class": "ISO 13679 Класс соединения",
  "Tubular Connection": "Трубное соединение",
  "Standard Casing/Tubing Service": "Стандартная эксплуатация обсадных/НКТ колонн",
  "Standard Torque & Tension Envelopes": "Стандартные диаграммы крутящего момента и растяжения",
  "ISO 13679 CAL IV (Gas Tight)": "ISO 13679 CAL IV (Газогерметичное)",
  "Premium Metal-to-Metal Seal Connection": "Премиальное соединение с уплотнением металл-металл",
  "High Pressure Gas Wells / HPHT / Critical": "Высоконапорные газовые скважины / HPHT / Ответственные интервалы",
  "100% Tension/Compression Load Gas Tight": "100% герметичность при растяжении и сжатии",

  // --- Elastomers profiles ---
  "ASTM D1418 FKM": "ASTM D1418 FKM",
  "ISO 1629 FKM": "ISO 1629 FKM",
  "Fluorocarbon Elastomer (FKM)": "Фторкаучук (FKM / Viton)",
  "Sour Service & High Temperature": "Среды с H₂S и высокая температура",
  "Temp: -20°C to 204°C, Exceptional Acid Resist.": "Темп: от -20°C до 204°C, исключительная кислотостойкость",
  "ASTM D1418 NBR": "ASTM D1418 NBR",
  "ISO 1629 NBR": "ISO 1629 NBR",
  "Nitrile Rubber (NBR)": "Бутадиен-нитрильный каучук (NBR)",
  "General Oilfield Fluid Service (Sweet)": "Стандартные среды без сероводорода (Sweet)",
  "Temp: -30°C to 120°C, Low H₂S/Amine": "Темп: от -30°C до 120°C, низкая стойкость к H₂S/аминам",
  "ASTM D1418 HNBR": "ASTM D1418 HNBR",
  "ISO 1629 HNBR": "ISO 1629 HNBR",
  "Hydrogenated Nitrile Elastomer": "Гидрированный бутадиен-нитрильный каучук (HNBR)",
  "High Temperature & H₂S Fluid Service": "Высокие температуры и среды с содержанием H₂S",
  "Temp: -30°C to 150°C, Good H₂S/Amine": "Темп: от -30°C до 150°C, хорошая стойкость к H₂S/аминам",
  "ASTM D1418 / ISO 1629": "ASTM D1418 / ISO 1629",
  "ISO 1629 Polymer Class": "ISO 1629 Класс полимера",
  "Polymer / Elastomer": "Полимер / Эластомер",
  "Oilfield Fluid Seal Service": "Уплотнение промысловых сред",
  "Material Specific Limits": "Лимиты зависят от свойств материала",
  "ASTM D1418 FFKM/FEPM": "ASTM D1418 FFKM/FEPM",
  "ISO 1629 FFKM/FEPM": "ISO 1629 FFKM/FEPM",
  "Perfluoroelastomer (FFKM/Aflas Class)": "Перфторкаучук (FFKM / Aflas)",
  "Extreme HPHT Chemical & Steam Service": "Экстремальные HPHT условия, агрессивная химия и пар",
  "Temp: -20°C to 260°C+, Universal Seal": "Темп: от -20°C до 260°C+, универсальное уплотнение",
  
  // --- Linked Equipment, Steels & Scopes ---
  "Production liner": "Эксплуатационный хвостовик",
  "Deep intermediate casing": "Глубокая промежуточная обсадная колонна",
  "Q125 High-Strength Steel": "Высокопрочная сталь Q125",
  "VM125HC High-Collapse Steel": "Высокопрочная сталь с сопротивлением к смятию VM125HC",
  "REFERENCE": "Справочный",
  "General Completion Guidelines": "Общие рекомендации по заканчиванию",
  "Verify with local operator procedures": "Проверить в соответствии с процедурами местного оператора",
  "Deepwater offshore completions": "Глубоководные морские заканчивания",
  "Production tubing": "Эксплуатационные НКТ",
  "Intermediate casing strings": "Промежуточные обсадные колонны",
  "Production casing strings": "Эксплуатационные обсадные колонны",
  "Intermediate casing": "Промежуточная колонна",
  "Production casing": "Эксплуатационная колонна",
  "Conductor casing": "Направление",
  "Intermediate sections": "Промежуточные секции",
  "Surface casing": "Кондуктор",
  "Standard completion strings": "Стандартные компоновки заканчивания",
  "Artificial lift (ESP/Rod pump)": "Механизированная добыча (УЭЦН/ШГН)",
  "Low-pressure production wells": "Низконапорные эксплуатационные скважины",
  "Water injection/disposal wells": "Нагнетательные/поглощающие скважины",
  "Sweet production gas": "Слабокислый добываемый газ",
  "Standard intermediate casing": "Стандартная промежуточная обсадная колонна",
  "HPHT production strings": "Высоконагруженные эксплуатационные колонны HPHT",
  "Deep high-pressure reservoirs": "Глубокие коллекторы с высоким давлением",
  "High-pressure casing strings": "Высоконапорные обсадные колонны",
  "Salt zone completions": "Заканчивания в солевых интервалах",
  "Critical sour completions": "Критические заканчивания в кислых средах",
  "Deep sour completions": "Глубокие заканчивания в кислых средах",
  "High-pressure production casing": "Высоконапорные эксплуатационные обсадные колонны",
  "HPHT tubing completions": "Колонны НКТ для условий HPHT",
  "Casing drilling": "Бурение на обсадной колонне",
  "Production liners": "Эксплуатационные хвостовики",
  "High-torque casing drilling": "Высокомоментное бурение на обсадной колонне",
  "L80 Carbon Steel": "Углеродистая сталь L80",
  "P110 Carbon Steel": "Углеродистая сталь P110",
  "Q125 Carbon Steel": "Углеродистая сталь Q125",
  "J55 Tubing": "НКТ J55",
  "L80 Tubing": "НКТ L80",
  "G105 Drill Pipe": "Бурильная труба G105",
  "J55 Casing": "Обсадная труба J55",
  "K55 Casing": "Обсадная труба K55",
  "N80 Casing": "Обсадная труба N80",
  "L80 Casing": "Обсадная труба L80",
  "P110 Casing": "Обсадная труба P110",
  "Q125 Casing": "Обсадная труба Q125",
  "S135 Drill Pipe": "Бурильная труба S135",
  "E75 Drill Pipe": "Бурильная труба E75",
  "X95 Drill Pipe": "Бурильная труба X95",
  "J55 Carbon Steel": "Углеродистая сталь J55",
  "K55 Carbon Steel": "Углеродистая сталь K55",
  "N80 Type 1 Steel": "Сталь N80 Тип 1",
  "N80Q Carbon Steel": "Сталь N80Q",
  "L80 Type 1 Carbon Steel": "Углеродистая сталь L80 Тип 1",
  "L80 13Cr Martensitic Steel": "Мартенситная сталь L80 13Cr",
  "C90 Sour Service Steel": "Сталь для кислых сред C90",
  "T95 Sour Service Steel": "Сталь для кислых сред T95",
  "VM125HC High-Collapse Steel": "Высокопрочная сталь с сопротивлением к смятию VM125HC",
  "22Cr Duplex Stainless Steel": "Двухфазная нержавеющая сталь 22Cr",
  "25Cr Super Duplex Steel": "Супердуплексная сталь 25Cr",
  "Inconel 625 (Nickel CRA)": "Никелевый сплав Inconel 625",
  "Incoloy 825 (Nickel-Iron-Chromium CRA)": "Никель-железо-хромовый сплав Incoloy 825",
  "Monel 400 (Nickel-Copper Alloy)": "Никель-медный сплав Monel 400",
  
  // --- Threads specific parameters ---
  "Standard API envelope.": "Стандартная диаграмма API.",
  "CAL-IV qualified, max torque up to 8,500 ft-lbs.": "Сертифицировано по CAL-IV, макс. момент до 8 500 фут-фунтов.",
  "CAL-IV qualified, high torque capacity.": "Сертифицировано по CAL-IV, высокая стойкость к крутящему моменту.",
  "Max torque up to 12,000 ft-lbs depending on wall thickness.": "Макс. момент до 12 000 фут-фунтов в зависимости от толщины стенки.",
  "Symmetric envelope with solid shoulder feedback.": "Симметричная диаграмма с чётко выраженным моментом посадки на торец.",
  "Broad envelope due to localized pitch design.": "Широкий рабочий диапазон благодаря конструкции переменного шага.",
  "Very high yield limits.": "Очень высокие пределы текучести.",
  "Lower torque limits due to slim joint design.": "Более низкие пределы момента из-за муфты уменьшенного диаметра.",
  "Exceptional torque limits.": "Исключительные пределы крутящего момента.",
  "Low torque envelope due to flush wall thickness.": "Узкий диапазон момента из-за безмуфтового соединения.",
  "Highest torque capability in industry.": "Наивысшая крутящая способность в индустрии.",
  "Not rated for gas pressure, interference seal only.": "Не рассчитано на давление газа, уплотнение только за счет натяга резьбы.",
  "100% gas-tight under ISO 13679 CAL-IV.": "100% газогерметичность согласно ISO 13679 CAL-IV.",
  "CAL-IV certified gas-tight.": "Газогерметичность сертифицирована по CAL-IV.",
  "Certified gas-tight under ISO 13679 CAL-IV.": "Сертифицировано как газогерметичное по ISO 13679 CAL-IV.",
  "CAL-IV certified.": "Сертифицировано по CAL-IV.",
  "Certified gas-tight.": "Сертифицировано как газогерметичное.",
  "Gas-tight under standard conditions.": "Газогерметично при стандартных условиях.",
  "Highly reliable fluid seal, not CAL-IV certified gas-tight.": "Высоконадежное гидравлическое уплотнение, без сертификации газогерметичности CAL-IV.",
  "Standard tension efficiency.": "Стандартная эффективность при растяжении.",
  "Compression load capability equals 100% of pipe body yield.": "Стойкость к сжатию равна 100% от предела текучести тела трубы.",
  "Compression capability is 100% of pipe body.": "Стойкость к сжимающей нагрузке составляет 100% от прочности тела трубы.",
  "100% compression rating matching pipe body yield.": "100% стойкость к сжатию относительно предела текучести тела трубы.",
  "Excellent compression performance; equal to standard Tenaris Blue.": "Отличная стойкость к сжатию, аналогично стандартному Tenaris Blue.",
  "Excellent tension efficiency.": "Отличная эффективность при растяжении.",
  "High compression rating.": "Высокая стойкость к сжимающим нагрузкам.",
  "Reduced tension capability compared to coupling joints.": "Сниженная прочность на растяжение по сравнению с муфтовыми соединениями.",
  "100% tension efficiency.": "100% эффективность при растяжении.",
  "Reduced tension capacity compared to PH6.": "Сниженная прочность на растяжение по сравнению с PH6.",
  "Extreme tension and bending resistance.": "Экстремальная стойкость к растяжению и изгибу.",
  "High risk in CRA materials, moderate risk in carbon steels.": "Высокий риск для коррозионно-стойких сплавов (CRA), умеренный для углеродистых сталей.",
  "Moderate. Requires standard copper/zinc-based compounds.": "Умеренный. Требует применения стандартных медно-цинковых резьбовых смазок.",
  "Low. Dry lubricant coating protects pins and boxes.": "Низкий. Заводское сухое смазочное покрытие защищает ниппель и муфту.",
  "Low. Pitch change minimizes contact pressure.": "Низкий. Переменный шаг резьбы снижает контактное давление.",
  "Moderate. Heavy wall thickness requires good lubrication.": "Умеренный. Большая толщина стенки требует качественной смазки.",
  "Moderate to High. Slim profile requires precise alignment.": "От умеренного до высокого. Тонкий профиль требует точной центровки.",
  "Low. Two-step design limits initial thread contact.": "Низкий. Двухступенчатая конструкция ограничивает начальный контакт витков.",
  "Moderate. Flush joints have thinner sections.": "Умеренный. Безмуфтовые соединения имеют меньшую толщину стенок.",
  "Low. Heavy tool joint geometry prevents galling.": "Низкий. Тяжелая геометрия замкового соединения предотвращает задиры.",
  "Follow API running guidelines.": "Следуйте рекомендациям API по спуску.",
  "Use computer-aided torque-turn analyzer.": "Используйте компьютерный анализатор крутящего момента и оборотов.",
  "Run slowly, align precisely.": "Спускать медленно, центрировать с высокой точностью.",
  "Use torque-turn monitoring equipment.": "Используйте оборудование для мониторинга крутящего момента и оборотов.",
  "Keep thread protector on until final stabbing.": "Не снимайте предохранитель резьбы до момента посадки.",
  "Run at low RPM to ensure even thread loading.": "Свинчивать на низких оборотах для равномерного распределения нагрузки.",
  "Strict torque-turn monitoring.": "Строгий контроль крутящего момента и оборотов.",
  "Use stabilizer/alignment clamps.": "Используйте стабилизирующие центрирующие хомуты.",
  "Align joints perfectly before stabbing.": "Идеально центрируйте соединения перед посадкой.",
  "Use light stabbing guide.": "Используйте легкое направляющее устройство для посадки.",
  "Clean tool joint threads thoroughly after each trip.": "Тщательно очищайте резьбу замка после каждого подъема.",
  "API modified compound, metal-free premium greases.": "Модифицированная смазка API, премиальные безметаллические смазки.",
  "Tenaris approved lubricants.": "Одобренные Tenaris смазочные материалы.",
  "API modified compound, metal-free thread dopes.": "Модифицированная смазка API, безметаллические резьбовые пасты.",
  "None (dry-film lubricant factory applied).": "Отсутствуют (заводское сухое смазочное покрытие).",
  "API modified compound, metal-free dopes.": "Модифицированная смазка API, безметаллические уплотнительные смазки.",
  "Standard API compounds.": "Стандартные резьбовые смазки API.",
  "API modified compound.": "Модифицированная резьбовая смазка API.",
  "Copper-based or zinc-based drill pipe dopes.": "Медные или цинковые смазки для бурильных труб.",
  "Inspect metal seal area for scratches before stabbing.": "Проверьте зону металлического уплотнения на предмет царапин перед посадкой.",
  "Clean box carefully to remove shipping grease.": "Тщательно очистите муфту от консервационной смазки.",
  "Inspect shoulder contact carefully.": "Тщательно проверяйте контакт упорного торца.",
  "Dry clean only. Water/oil on threads can cause makeup errors.": "Только сухая очистка. Вода или масло на резьбе могут вызвать ошибки свинчивания.",
  "Visual check of shoulder alignment is critical.": "Визуальный контроль центровки торцов критически важен.",
  "Ensure no mud enters pin or box.": "Не допускайте попадания бурового раствора в ниппель или муфту.",
  "Double check pin shoulder contact.": "Дважды проверьте контакт упорного уступа ниппеля.",
  "Ensure double shoulder contacts are clean.": "Убедитесь в чистоте контактов двойного упорного уступа.",
  "Examine thin box area for damage.": "Осмотрите тонкую зону муфты на наличие повреждений.",
  "Verify secondary shoulder contact visually.": "Визуально проверьте контакт вторичного упорного уступа.",
  "API Tubing Upset": "API соединение с высаженными концами (НКТ)",
  "API Casing Buttress": "API обсадное трапецеидальное соединение (Buttress)",
  "European Premium Metal-Metal": "Европейское премиальное с металлическим уплотнением",
  "Tenaris Premium Gas-Tight": "Премиальное газогерметичное соединение Tenaris",
  "Chinese Premium Gas-Tight": "Китайское премиальное газогерметичное соединение",
  "European Premium High-Torque": "Европейское высокомоментное премиальное соединение",
  "Tenaris Dope-Free Premium": "Премиальное соединение Tenaris Dope-Free (без смазки)",
  "JFE Premium Thread": "Премиальное резьбовое соединение JFE",
  "Proprietary Premium Thread": "Запатентованное премиальное резьбовое соединение",
  "Slim-Hole Premium": "Премиальное соединение уменьшенного диаметра (Slim-Hole)",
  "Two-Step Premium": "Двухступенчатое премиальное соединение",
  "Flush Two-Step Premium": "Безмуфтовое двухступенчатое премиальное соединение",
  "Double-Shoulder Drill Pipe": "Замковое соединение с двойным упорным уступом",
  "Thread interference seal": "Резьбовой натяг (герметизация по виткам)",
  "Mechanical thread interference": "Механический резьбовой натяг",
  "Metal-to-metal radial seal": "Радиальное уплотнение металл-металл",
  "Sphere-to-cone metal-to-metal seal": "Радиальное уплотнение сфера-конус металл-металл",
  "Metal-to-metal radial seal with external shoulder": "Радиальное уплотнение металл-металл с внешним упором",
  "Dope-free metal-to-metal seal": "Безремонтное уплотнение металл-металл Dope-free",
  "Metal-to-metal seal": "Уплотнение металл-металл",
  "Double metal-to-metal seal": "Двойное уплотнение металл-металл",
  "Double shoulder metal-to-metal seal": "Уплотнение металл-металл с двойным упором",
  "1.5 threads": "1.5 витка",
  "1.0 threads": "1.0 витка",
  "0 (Shoulder contact)": "0 (контакт упорного торца)",
  "0 (Torque shoulder)": "0 (упор в торец)",
  "0 (Shoulder stop)": "0 (упорный торец)",
  "Torque-turn controlled shoulder makeup": "Контроль свинчивания по крутящему моменту и углу поворота",
  "Direct wedge mating verification": "Контроль клинового сопряжения",
  "0 (Shoulder)": "0 (упорный торец)",
  "0 (Double shoulder)": "0 (двойной упорный уступ)",
  
  // --- Threads description translations ---
  "Standard API connection with external upset on tubing ends for standard oilfield completions.": "Стандартное резьбовое соединение API с высаженными концами труб для стандартных условий эксплуатации.",
  "API standard casing connection with buttress profile, offering high tensile strength.": "Стандартное резьбовое соединение API для обсадных труб с трапецеидальной резьбой (Buttress), обеспечивающее высокую прочность на растяжение.",
  "Standard Russian trapezoidal thread connection for casing strings.": "Стандартное российское трапецеидальное резьбовое соединение для обсадных колонн по ГОСТ 632.",
  "Russian premium casing connection with metal-to-metal seal and torque shoulder.": "Российское премиальное соединение для обсадных колонн с уплотнением металл-металл и упорным торцом.",
  "Premium gas-tight threaded connection for casing and tubing with metal-to-metal seal.": "Премиальное газогерметичное резьбовое соединение для обсадных и насосно-компрессорных труб с уплотнением металл-металл.",
  "Premium gas-tight connection with double torque shoulder and high compression rating.": "Премиальное газогерметичное соединение с двойным упорным уступом и высоким сопротивлением сжатию.",
  "Russian premium gas-tight connection family for tubing and casing with metal-to-metal seals.": "Семейство российских премиальных газогерметичных соединений для НКТ и обсадных труб с уплотнениями металл-металл.",
  "Chinese premium connection with high torque capacity and metal-to-metal seal.": "Китайское премиальное соединение с высокой крутящей способностью и уплотнением металл-металл.",
  "Next-generation premium connection featuring a unique threaded sleeve design and 100% burst/collapse envelope rating.": "Премиальное соединение нового поколения с уникальной конструкцией резьбовой муфты и 100% стойкостью к внутреннему и внешнему давлению.",
  "Premium integral connection utilizing a dovetail wedge thread profile that provides high torque capability without a torque shoulder.": "Премиальное интегральное соединение с клиновым профилем резьбы типа «ласточкин хвост», обеспечивающее высокую крутящую способность без упорного торца.",
  "Premium connection designed for high torque applications in drilling and casing strings.": "Премиальное соединение, разработанное для применения при высоких крутящих моментах в бурильных и обсадных колоннах.",
  "Dry premium connection requiring no thread compound (dope-free) for environmental safety.": "Премиальное соединение сухого свинчивания, не требующее резьбовой смазки (Dope-Free), для экологической безопасности.",
  "Premium casing/tubing thread designed with a unique pitch change to distribute load and reduce galling.": "Премиальная резьба для обсадных и насосно-компрессорных труб с переменным шагом для равномерного распределения нагрузки и снижения риска задиров.",
  "High-collapse premium casing thread optimized for thick-wall salt zone casings.": "Высокогерметичная премиальная резьба для обсадных труб, оптимизированная для толстостенных колонн в солевых интервалах.",
  "Standard flushing joint premium connection with gas-tight seal for slim-hole completions.": "Стандартное премиальное безмуфтовое соединение с газогерметичным уплотнением для заканчивания скважин малого диаметра.",
  "Two-step premium tubing connection with high tensile efficiency and gas-tight seal.": "Двухступенчатое премиальное соединение для НКТ с высокой эффективностью на растяжение и газогерметичным уплотнением.",
  "Standard two-step premium tubing connection with flush joint profile for clearance wells.": "Стандартное двухступенчатое премиальное соединение для НКТ с гладким (безмуфтовым) профилем для скважин с малым зазором.",
  "Drill pipe premium connection designed for extreme torsional loads in directional and ERD wells.": "Премиальное соединение для бурильных труб, разработанное для экстремальных крутящих моментов в наклонно-направленных скважинах и скважинах с большим отходом (ERD)."
};

/**
 * Translates English database and profile text to Russian.
 * 
 * @param {string} text - The input English string.
 * @param {string} lang - Selected language ('ru' or 'en').
 * @returns {string} Translated string or original text.
 */
export function translateDbText(text, lang) {
  if (lang !== 'ru' || !text) return text;
  
  const trimmed = String(text).trim();
  if (DB_TRANSLATIONS[trimmed]) {
    return DB_TRANSLATIONS[trimmed];
  }

  // Handle minor character variations (e.g. trailing dots, spaces)
  const normalized = trimmed.replace(/\.$/, '');
  if (DB_TRANSLATIONS[normalized]) {
    return DB_TRANSLATIONS[normalized] + (trimmed.endsWith('.') ? '.' : '');
  }

  return text;
}

export default { translateDbText };
