/**
 * databaseTranslator.js
 * Dictionary and helper to translate dynamic English database strings
 * and standard alignment profiles to Russian when selected.
 */

const DB_TRANSLATIONS = {
  // --- Tubulars specific lists (advantages, limitations, applications) ---
  "Controlled yield strength for mild sour service": "Контролируемый предел текучести для слабокислых сред",
  "Good collapse resistance": "Хорошее сопротивление смятию",
  "Not for high H2S concentrations": "Не подходит для высоких концентраций H₂S",
  "Medium pressure limit": "Средний лимит давления",
  "Intermediate casing sections": "Промежуточные секции обсадных колонн",
  "Medium-depth wells": "Скважины средней глубины",
  "Highly ductile": "Высокая пластичность",
  "Very economic choice": "Очень экономичный выбор",
  "Standard global availability": "Стандартная глобальная доступность",
  "Low corrosion resistance in sour gas": "Низкая коррозионная стойкость в кислом газе",
  "Low collapse rating": "Низкое сопротивление смятию",
  "Low-pressure production wells": "Низконапорные эксплуатационные скважины",
  "Water injection/disposal wells": "Нагнетательные/водозаборные скважины",
  "Sour service compatibility (NACE MR0175 compliance)": "Совместимость с кислыми средами (соответствие NACE MR0175)",
  "Good tensile strength": "Хорошая прочность на растяжение",
  "Not suitable for high CO2 with high watercut without inhibition": "Не подходит для высокого содержания CO₂ с высокой обводненностью без ингибирования",
  "Standard production wells with mild H2S": "Стандартные добывающие скважины со слабым содержанием H₂S",
  "Deep completion strings": "Глубокие эксплуатационные колонны",
  "Excellent Sulfide Stress Cracking (SSC) resistance": "Отличное сопротивление сульфидному растрескиванию под напряжением (РКН)",
  "Very high collapse ratings": "Очень высокая стойкость к смятию",
  "Higher cost": "Более высокая стоимость",
  "Susceptible to severe CO2 corrosion in wet gas without inhibitors": "Подвержен сильной углекислотной коррозии во влажном газе без ингибиторов",
  "Severe H2S wells": "Скважины с высоким содержанием H₂S",
  "Deep sour gas completions": "Глубокие газовые скважины с кислыми средами",
  "High-stress production strings": "Высоконагруженные эксплуатационные колонны",
  "Exceptional tensile and burst ratings": "Исключительная прочность на растяжение и внутреннее давление",
  "Suitable for deep vertical wells": "Подходит для глубоких вертикальных скважин",
  "Not resistant to H2S (SSC hazard)": "Неустойчив к H₂S (риск сульфидного растрескивания)",
  "Strict temperature limits under stress": "Строгие температурные ограничения под нагрузкой",
  "Deep sweet gas completions": "Глубокие газовые скважины со сладкими средами",
  "High-pressure wells": "Скважины с высоким давлением (HP)",
  "Maximum yield strength": "Максимальный предел текучести",
  "High collapse resistance for deep reservoirs": "Высокое сопротивление смятию для глубоких коллекторов",
  "No H2S resistance (very brittle in sour environment)": "Нет стойкости к H₂S (хрупкое разрушение в кислой среде)",
  "Deep gas wells": "Глубокие газовые скважины",
  "HPHT reservoir sections": "Интервалы пластов с АВПД и АВТ (HPHT)",
  "Great balance of tensile strength and price": "Отличный баланс прочности на растяжение и цены",
  "Wide availability": "Широкая доступность",
  "High susceptibility to SSC in H2S environments": "Высокая чувствительность к сульфидному растрескиванию в средах H₂S",
  "Intermediate sections in deep wells": "Промежуточные секции глубоких скважин",
  "Production casing in sweet wells": "Эксплуатационные колонны в сладких скважинах",
  "Economic surface protection": "Экономичная защита кондуктора",
  "Ductile and easily welded": "Пластичный и легко свариваемый",
  "Low collapse threshold": "Низкий порог смятия",
  "No acid/H2S resistance": "Отсутствие стойкости к кислотам и H₂S",
  "Surface hole isolation": "Изоляция верхних интервалов",
  "Water aquifer protection": "Защита водоносных горизонтов",
  "High structural bending capacity": "Высокая изгибающая способность конструкции",
  "Cheap, easy to weld/joint": "Дешевый, простой монтаж/сварка",
  "Low burst and collapse rating": "Низкая прочность на разрыв и смятие",
  "Heavy weight per unit length": "Большой вес на единицу длины",
  "Structural casing sections": "Направление (структурная колонна)",
  "Top-hole drilling stabilization": "Стабилизация устья при бурении под направление",
  "Light weight": "Легкий вес",
  "Excellent flexibility in high dogleg severities": "Отличная гибкость в интервалах с высокой интенсивностью искривления",
  "Low torsional limit compared to high grades": "Низкий крутящий момент по сравнению с высокопрочными группами",
  "Slim hole drilling": "Бурение малым диаметром",
  "Coiled tubing and workover operations": "Колтюбинг и ремонтные работы",
  "Balanced tensile-to-weight ratio": "Сбалансированное отношение прочности к весу",
  "Good fatigue resistance": "Хорошая усталостная прочность",
  "Limited sour service compatibility": "Ограниченная совместимость с кислыми средами",
  "Directional drilling": "Направленное бурение",
  "Standard workovers": "Стандартное КРС",
  "High ductility": "Высокая пластичность",
  "Good fatigue life in abrasive wells": "Хороший усталостный ресурс в абразивных скважинах",
  "Lower tensile limit than S135": "Более низкий предел прочности, чем у S135",
  "Intermediate hole section drilling": "Бурение под промежуточную колонну",
  "Medium torque operations": "Операции со средним крутящим моментом",
  "Maximum tensile limit": "Максимальный предел прочности",
  "High torsional capacity": "Высокая крутящая способность",
  "Excellent fatigue limits": "Отличная усталостная прочность",
  "Highly susceptible to sulfide stress cracking in H2S": "Очень высокая чувствительность к сульфидному растрескиванию в H₂S",
  "High cost": "Высокая стоимость",
  "Deep drilling": "Глубокое бурение",
  "Extended reach drilling (ERD)": "Бурение с большим отходом от вертикали (ERD)",
  "High torque operations": "Операции с высоким крутящим моментом",
  "Very high tensile rating": "Очень высокая прочность на растяжение",
  "Lower pressure drop due to large ID": "Низкий перепад давления благодаря большому ВД",
  "Very heavy, requires high capacity rigs": "Очень тяжелый, требует буровых установок большой грузоподъемности",
  "Extremely stiff": "Чрезвычайно жесткий",
  "Extended reach horizontal drilling": "Горизонтальное бурение с большим отходом",
  "Deep marine gas wells": "Глубокие морские газовые скважины",

  // --- Used in equipment ---
  "Intermediate casing strings": "Промежуточные обсадные колонны",
  "Production casing strings": "Эксплуатационные обсадные колонны",
  "Conductor casing": "Направление (кондуктор)",
  "Structural liners": "Структурные хвостовики",
  "Coiled tubing reels": "Барабаны колтюбинга",
  "Workover strings": "Колонны ГТМ / КРС",
  "Drill strings": "Бурильные колонны",
  "High dogleg sections": "Интервалы с высокой интенсивностью искривления",
  "Severe environments": "Агрессивные среды",
  "Deep vertical sections": "Глубокие вертикальные секции",
  "Extended reach sections": "Секции с большим отходом",

  // --- Standard Classification profiles ---
  "API Spec 5CT (High Strength)": "API Spec 5CT (Высокопрочная)",
  "ISO 11960 Group 3": "ISO 11960 Группа 3",
  "High Strength Carbon Steel": "Высокопрочная углеродистая сталь",
  "Sweet Service Only (No H₂S)": "Только для слабокислых сред (без H₂S)",
  "Yield: 110-140 ksi, Temp: Stable": "Текучесть: 110-140 ksi, Стабильная темп.",
  "API Spec 5CT / NACE MR0175": "API Spec 5CT / NACE MR0175",
  "ISO 13680 / ISO 15156 (CRA)": "ISO 13680 / ISO 15156 (CRA)",
  "Corrosion Resistant Alloy (13Cr CRA)": "Коррозионно-стойкий сплав (13Cr CRA)",
  "Sour Service Capable (H₂S + CO₂)": "Подходит для кислых сред (H₂S + CO₂)",
  "Yield: Min 80 ksi, NACE MR0175 Limits Apply": "Текучесть: мин. 80 ksi, лимиты NACE MR0175",
  "API Spec 5CT (Group 2, L80)": "API Spec 5CT (Группа 2, L80)",
  "ISO 11960 Group 2": "ISO 11960 Группа 2",
  "Controlled Hardness Carbon Steel": "Углеродистая сталь контролируемой твердости",
  "Sour Service Capable (H₂S Suitable)": "Подходит для кислых сред (H₂S Suitable)",
  "Yield: 80-95 ksi, Max Hardness 23 HRC": "Текучесть: 80-95 ksi, макс. твердость 23 HRC",
  "API Spec 5CT (Group 4, Q125)": "API Spec 5CT (Группа 4, Q125)",
  "ISO 11960 Group 4": "ISO 11960 Группа 4",
  "Ultra High Strength Carbon Steel": "Ультравысокопрочная углеродистая сталь",
  "Sweet Service (Special H₂S limits)": "Слабокислая среда (спец. лимиты H₂S)",
  "Yield: 125-150 ksi, Critical Design Only": "Текучесть: 125-150 ksi, только ответственные конструкции",
  "ISO 13680 / ISO 15156": "ISO 13680 / ISO 15156",
  "Corrosion Resistant Alloy (CRA)": "Коррозионно-стойкий сплав (CRA)",
  "Sour Service Capable (High CO₂ / Mild H₂S)": "Подходит для кислых сред (высокий CO₂ / слабый H₂S)",
  "Yield: Min 95-110 ksi, Max Temp 180°C": "Текучесть: мин. 95-110 ksi, макс. темп. 180°C",
  "NACE MR0175 / ISO 15156 (CRA)": "NACE MR0175 / ISO 15156 (CRA)",
  "ISO 13680 (High CRA)": "ISO 13680 (Высоколегированный CRA)",
  "Super Corrosion Resistant Alloy (High Al)": "Суперкоррозионностойкий сплав (High Al)",
  "Severe HPHT Sour & High Chloride": "Агрессивный HPHT флюид (кислый и с хлоридами)",
  "Extreme Resistance to Pit & SSC Corrosion": "Экстремальная стойкость к питтингу и сульфидному растрескиванию",
  "API Spec 5CT": "API Spec 5CT",
  "ISO 11960": "ISO 11960",
  "Oilfield Steel Grade": "Промысловый сорт стали",
  "Standard Casing & Tubing Service": "Стандартная эксплуатация обсадных и НКТ колонн",
  "Grade Dependent Limits": "Лимиты зависят от группы прочности",

  // --- Connections / Threads profiles ---
  "API Spec 5B (Standard Thread)": "API Spec 5B (Стандартная резьба)",
  "ISO 11960 (API Threads)": "ISO 11960 (Резьбы API)",
  "Standard API Thread Connection": "Стандартное резьбовое соединение API",
  "Moderate Tension & Low Pressure Service": "Умеренное растяжение и низкое рабочее давление",
  "Grease Dependent Helical Thread Seal": "Герметизация витков за счет резьбовой смазки",
  "API Spec 5B / ISO 13679": "API Spec 5B / ISO 13679",
  "ISO 13679 Connection Class": "ISO 13679 Класс соединения",
  "Tubular Connection": "Трубное соединение",
  "Standard Casing/Tubing Service": "Стандартная эксплуатация обсадных/НКТ колонн",
  "Standard Torque & Tension Envelopes": "Стандартные диаграммы крутящего момента и растяжения",
  "ISO 13679 CAL IV (Gas Tight)": "ISO 13679 CAL IV (Газогерметичное)",
  "Premium Metal-to-Metal Seal Connection": "Премиальное соединение с уплотнением металл-металл",
  "High Pressure Gas Wells / HPHT / Critical": "Высоконапорные газовые скважины / HPHT / Ответственные интервалы",
  "100% Tension/Compression Load Gas Tight": "100% герметичность при растяжении и сжатии",

  // --- Elastomers profiles ---
  "ASTM D1418 FKM": "ASTM D1418 FKM",
  "ISO 1629 FKM": "ISO 1629 FKM",
  "Fluorocarbon Elastomer (FKM)": "Фторкаучук (FKM / Viton)",
  "Sour Service & High Temperature": "Среды с H₂S и высокая температура",
  "Temp: -20°C to 204°C, Exceptional Acid Resist.": "Темп: от -20°C до 204°C, исключительная кислотостойкость",
  "ASTM D1418 NBR": "ASTM D1418 NBR",
  "ISO 1629 NBR": "ISO 1629 NBR",
  "Nitrile Rubber (NBR)": "Бутадиен-нитрильный каучук (NBR)",
  "General Oilfield Fluid Service (Sweet)": "Стандартные среды без сероводорода (Sweet)",
  "Temp: -30°C to 120°C, Low H₂S/Amine": "Темп: от -30°C до 120°C, низкая стойкость к H₂S/аминам",
  "ASTM D1418 HNBR": "ASTM D1418 HNBR",
  "ISO 1629 HNBR": "ISO 1629 HNBR",
  "Hydrogenated Nitrile Elastomer": "Гидрированный бутадиен-нитрильный каучук (HNBR)",
  "High Temperature & H₂S Fluid Service": "Высокие температуры и среды с содержанием H₂S",
  "Temp: -30°C to 150°C, Good H₂S/Amine": "Темп: от -30°C до 150°C, хорошая стойкость к H₂S/аминам",
  "ASTM D1418 / ISO 1629": "ASTM D1418 / ISO 1629",
  "ISO 1629 Polymer Class": "ISO 1629 Класс полимера",
  "Polymer / Elastomer": "Полимер / Эластомер",
  "Oilfield Fluid Seal Service": "Уплотнение промысловых сред",
  "Material Specific Limits": "Лимиты зависят от свойств материала",
  "ASTM D1418 FFKM/FEPM": "ASTM D1418 FFKM/FEPM",
  "ISO 1629 FFKM/FEPM": "ISO 1629 FFKM/FEPM",
  "Perfluoroelastomer (FFKM/Aflas Class)": "Перфторкаучук (FFKM / Aflas)",
  "Extreme HPHT Chemical & Steam Service": "Экстремальные HPHT условия, агрессивная химия и пар",
  "Temp: -20°C to 260°C+, Universal Seal": "Темп: от -20°C до 260°C+, универсальное уплотнение",
  
  // --- Linked Equipment, Steels & Scopes ---
  "Production liner": "Эксплуатационный хвостовик",
  "Deep intermediate casing": "Глубокая промежуточная обсадная колонна",
  "Q125 High-Strength Steel": "Высокопрочная сталь Q125",
  "VM125HC High-Collapse Steel": "Высокопрочная сталь с сопротивлением к смятию VM125HC",
  "REFERENCE": "Справочный",
  "General Completion Guidelines": "Общие рекомендации по заканчиванию",
  "Verify with local operator procedures": "Проверить в соответствии с процедурами местного оператора",
  "Deepwater offshore completions": "Глубоководные морские заканчивания",
  "Production tubing": "Эксплуатационные НКТ",
  "Intermediate casing strings": "Промежуточные обсадные колонны",
  "Production casing strings": "Эксплуатационные обсадные колонны",
  "Intermediate casing": "Промежуточная колонна",
  "Production casing": "Эксплуатационная колонна",
  "Conductor casing": "Направление",
  "Intermediate sections": "Промежуточные секции",
  "Surface casing": "Кондуктор",
  "Standard completion strings": "Стандартные компоновки заканчивания",
  "Artificial lift (ESP/Rod pump)": "Механизированная добыча (УЭЦН/ШГН)",
  "Low-pressure production wells": "Низконапорные эксплуатационные скважины",
  "Water injection/disposal wells": "Нагнетательные/поглощающие скважины",
  "Sweet production gas": "Слабокислый добываемый газ",
  "Standard intermediate casing": "Стандартная промежуточная обсадная колонна",
  "HPHT production strings": "Высоконагруженные эксплуатационные колонны HPHT",
  "Deep high-pressure reservoirs": "Глубокие коллекторы с высоким давлением",
  "High-pressure casing strings": "Высоконапорные обсадные колонны",
  "Salt zone completions": "Заканчивания в солевых интервалах",
  "Critical sour completions": "Критические заканчивания в кислых средах",
  "Deep sour completions": "Глубокие заканчивания в кислых средах",
  "High-pressure production casing": "Высоконапорные эксплуатационные обсадные колонны",
  "HPHT tubing completions": "Колонны НКТ для условий HPHT",
  "Casing drilling": "Бурение на обсадной колонне",
  "Production liners": "Эксплуатационные хвостовики",
  "High-torque casing drilling": "Высокомоментное бурение на обсадной колонне",
  "L80 Carbon Steel": "Углеродистая сталь L80",
  "P110 Carbon Steel": "Углеродистая сталь P110",
  "Q125 Carbon Steel": "Углеродистая сталь Q125",
  "J55 Tubing": "НКТ J55",
  "L80 Tubing": "НКТ L80",
  "G105 Drill Pipe": "Бурильная труба G105",
  "J55 Casing": "Обсадная труба J55",
  "K55 Casing": "Обсадная труба K55",
  "N80 Casing": "Обсадная труба N80",
  "L80 Casing": "Обсадная труба L80",
  "P110 Casing": "Обсадная труба P110",
  "Q125 Casing": "Обсадная труба Q125",
  "S135 Drill Pipe": "Бурильная труба S135",
  "E75 Drill Pipe": "Бурильная труба E75",
  "X95 Drill Pipe": "Бурильная труба X95",
  "J55 Carbon Steel": "Углеродистая сталь J55",
  "K55 Carbon Steel": "Углеродистая сталь K55",
  "N80 Type 1 Steel": "Сталь N80 Тип 1",
  "N80Q Carbon Steel": "Сталь N80Q",
  "L80 Type 1 Carbon Steel": "Углеродистая сталь L80 Тип 1",
  "L80 13Cr Martensitic Steel": "Мартенситная сталь L80 13Cr",
  "C90 Sour Service Steel": "Сталь для кислых сред C90",
  "T95 Sour Service Steel": "Сталь для кислых сред T95",
  "VM125HC High-Collapse Steel": "Высокопрочная сталь с сопротивлением к смятию VM125HC",
  "22Cr Duplex Stainless Steel": "Двухфазная нержавеющая сталь 22Cr",
  "25Cr Super Duplex Steel": "Супердуплексная сталь 25Cr",
  "Inconel 625 (Nickel CRA)": "Никелевый сплав Inconel 625",
  "Incoloy 825 (Nickel-Iron-Chromium CRA)": "Никель-железо-хромовый сплав Incoloy 825",
  "Monel 400 (Nickel-Copper Alloy)": "Никель-медный сплав Monel 400",
  
  // --- Threads specific parameters ---
  "Standard API envelope.": "Стандартная диаграмма API.",
  "CAL-IV qualified, max torque up to 8,500 ft-lbs.": "Сертифицировано по CAL-IV, макс. момент до 8 500 фут-фунтов.",
  "CAL-IV qualified, high torque capacity.": "Сертифицировано по CAL-IV, высокая стойкость к крутящему моменту.",
  "Max torque up to 12,000 ft-lbs depending on wall thickness.": "Макс. момент до 12 000 фут-фунтов в зависимости от толщины стенки.",
  "Symmetric envelope with solid shoulder feedback.": "Симметричная диаграмма с чётко выраженным моментом посадки на торец.",
  "Broad envelope due to localized pitch design.": "Широкий рабочий диапазон благодаря конструкции переменного шага.",
  "Very high yield limits.": "Очень высокие пределы текучести.",
  "Lower torque limits due to slim joint design.": "Более низкие пределы момента из-за муфты уменьшенного диаметра.",
  "Exceptional torque limits.": "Исключительные пределы крутящего момента.",
  "Low torque envelope due to flush wall thickness.": "Узкий диапазон момента из-за безмуфтового соединения.",
  "Highest torque capability in industry.": "Наивысшая крутящая способность в индустрии.",
  "Not rated for gas pressure, interference seal only.": "Не рассчитано на давление газа, уплотнение только за счет натяга резьбы.",
  "100% gas-tight under ISO 13679 CAL-IV.": "100% газогерметичность согласно ISO 13679 CAL-IV.",
  "CAL-IV certified gas-tight.": "Газогерметичность сертифицирована по CAL-IV.",
  "Certified gas-tight under ISO 13679 CAL-IV.": "Сертифицировано как газогерметичное по ISO 13679 CAL-IV.",
  "CAL-IV certified.": "Сертифицировано по CAL-IV.",
  "Certified gas-tight.": "Сертифицировано как газогерметичное.",
  "Gas-tight under standard conditions.": "Газогерметично при стандартных условиях.",
  "Highly reliable fluid seal, not CAL-IV certified gas-tight.": "Высоконадежное гидравлическое уплотнение, без сертификации газогерметичности CAL-IV.",
  "Standard tension efficiency.": "Стандартная эффективность при растяжении.",
  "Compression load capability equals 100% of pipe body yield.": "Стойкость к сжатию равна 100% от предела текучести тела трубы.",
  "Compression capability is 100% of pipe body.": "Стойкость к сжимающей нагрузке составляет 100% от прочности тела трубы.",
  "100% compression rating matching pipe body yield.": "100% стойкость к сжатию относительно предела текучести тела трубы.",
  "Excellent compression performance; equal to standard Tenaris Blue.": "Отличная стойкость к сжатию, аналогично стандартному Tenaris Blue.",
  "Excellent tension efficiency.": "Отличная эффективность при растяжении.",
  "High compression rating.": "Высокая стойкость к сжимающим нагрузкам.",
  "Reduced tension capability compared to coupling joints.": "Сниженная прочность на растяжение по сравнению с муфтовыми соединениями.",
  "100% tension efficiency.": "100% эффективность при растяжении.",
  "Reduced tension capacity compared to PH6.": "Сниженная прочность на растяжение по сравнению с PH6.",
  "Extreme tension and bending resistance.": "Экстремальная стойкость к растяжению и изгибу.",
  "High risk in CRA materials, moderate risk in carbon steels.": "Высокий риск для коррозионно-стойких сплавов (CRA), умеренный для углеродистых сталей.",
  "Moderate. Requires standard copper/zinc-based compounds.": "Умеренный. Требует применения стандартных медно-цинковых резьбовых смазок.",
  "Low. Dry lubricant coating protects pins and boxes.": "Низкий. Заводское сухое смазочное покрытие защищает ниппель и муфту.",
  "Low. Pitch change minimizes contact pressure.": "Низкий. Переменный шаг резьбы снижает контактное давление.",
  "Moderate. Heavy wall thickness requires good lubrication.": "Умеренный. Большая толщина стенки требует качественной смазки.",
  "Moderate to High. Slim profile requires precise alignment.": "От умеренного до высокого. Тонкий профиль требует точной центровки.",
  "Low. Two-step design limits initial thread contact.": "Низкий. Двухступенчатая конструкция ограничивает начальный контакт витков.",
  "Moderate. Flush joints have thinner sections.": "Умеренный. Безмуфтовые соединения имеют меньшую толщину стенок.",
  "Low. Heavy tool joint geometry prevents galling.": "Низкий. Тяжелая геометрия замкового соединения предотвращает задиры.",
  "Follow API running guidelines.": "Следуйте рекомендациям API по спуску.",
  "Use computer-aided torque-turn analyzer.": "Используйте компьютерный анализатор крутящего момента и оборотов.",
  "Run slowly, align precisely.": "Спускать медленно, центрировать с высокой точностью.",
  "Use torque-turn monitoring equipment.": "Используйте оборудование для мониторинга крутящего момента и оборотов.",
  "Keep thread protector on until final stabbing.": "Не снимайте предохранитель резьбы до момента посадки.",
  "Run at low RPM to ensure even thread loading.": "Свинчивать на низких оборотах для равномерного распределения нагрузки.",
  "Strict torque-turn monitoring.": "Строгий контроль крутящего момента и оборотов.",
  "Use stabilizer/alignment clamps.": "Используйте стабилизирующие центрирующие хомуты.",
  "Align joints perfectly before stabbing.": "Идеально центрируйте соединения перед посадкой.",
  "Use light stabbing guide.": "Используйте легкое направляющее устройство для посадки.",
  "Clean tool joint threads thoroughly after each trip.": "Тщательно очищайте резьбу замка после каждого подъема.",
  "API modified compound, metal-free premium greases.": "Модифицированная смазка API, премиальные безметаллические смазки.",
  "Tenaris approved lubricants.": "Одобренные Tenaris смазочные материалы.",
  "API modified compound, metal-free thread dopes.": "Модифицированная смазка API, безметаллические резьбовые пасты.",
  "None (dry-film lubricant factory applied).": "Отсутствуют (заводское сухое смазочное покрытие).",
  "API modified compound, metal-free dopes.": "Модифицированная смазка API, безметаллические уплотнительные смазки.",
  "Standard API compounds.": "Стандартные резьбовые смазки API.",
  "API modified compound.": "Модифицированная резьбовая смазка API.",
  "Copper-based or zinc-based drill pipe dopes.": "Медные или цинковые смазки для бурильных труб.",
  "Inspect metal seal area for scratches before stabbing.": "Проверьте зону металлического уплотнения на предмет царапин перед посадкой.",
  "Clean box carefully to remove shipping grease.": "Тщательно очистите муфту от консервационной смазки.",
  "Inspect shoulder contact carefully.": "Тщательно проверяйте контакт упорного торца.",
  "Dry clean only. Water/oil on threads can cause makeup errors.": "Только сухая очистка. Вода или масло на резьбе могут вызвать ошибки свинчивания.",
  "Visual check of shoulder alignment is critical.": "Визуальный контроль центровки торцов критически важен.",
  "Ensure no mud enters pin or box.": "Не допускайте попадания бурового раствора в ниппель или муфту.",
  "Double check pin shoulder contact.": "Дважды проверьте контакт упорного уступа ниппеля.",
  "Ensure double shoulder contacts are clean.": "Убедитесь в чистоте контактов двойного упорного уступа.",
  "Examine thin box area for damage.": "Осмотрите тонкую зону муфты на наличие повреждений.",
  "Verify secondary shoulder contact visually.": "Визуально проверьте контакт вторичного упорного уступа.",
  "API Tubing Upset": "API соединение с высаженными концами (НКТ)",
  "API Casing Buttress": "API обсадное трапецеидальное соединение (Buttress)",
  "European Premium Metal-Metal": "Европейское премиальное с металлическим уплотнением",
  "Tenaris Premium Gas-Tight": "Премиальное газогерметичное соединение Tenaris",
  "Chinese Premium Gas-Tight": "Китайское премиальное газогерметичное соединение",
  "European Premium High-Torque": "Европейское высокомоментное премиальное соединение",
  "Tenaris Dope-Free Premium": "Премиальное соединение Tenaris Dope-Free (без смазки)",
  "JFE Premium Thread": "Премиальное резьбовое соединение JFE",
  "Proprietary Premium Thread": "Запатентованное премиальное резьбовое соединение",
  "Slim-Hole Premium": "Премиальное соединение уменьшенного диаметра (Slim-Hole)",
  "Two-Step Premium": "Двухступенчатое премиальное соединение",
  "Flush Two-Step Premium": "Безмуфтовое двухступенчатое премиальное соединение",
  "Double-Shoulder Drill Pipe": "Замковое соединение с двойным упорным уступом",
  "Thread interference seal": "Резьбовой натяг (герметизация по виткам)",
  "Mechanical thread interference": "Механический резьбовой натяг",
  "Metal-to-metal radial seal": "Радиальное уплотнение металл-металл",
  "Sphere-to-cone metal-to-metal seal": "Радиальное уплотнение сфера-конус металл-металл",
  "Metal-to-metal radial seal with external shoulder": "Радиальное уплотнение металл-металл с внешним упором",
  "Dope-free metal-to-metal seal": "Безремонтное уплотнение металл-металл Dope-free",
  "Metal-to-metal seal": "Уплотнение металл-металл",
  "Double metal-to-metal seal": "Двойное уплотнение металл-металл",
  "Double shoulder metal-to-metal seal": "Уплотнение металл-металл с двойным упором",
  "1.5 threads": "1.5 витка",
  "1.0 threads": "1.0 витка",
  "0 (Shoulder contact)": "0 (контакт упорного торца)",
  "0 (Torque shoulder)": "0 (упор в торец)",
  "0 (Shoulder stop)": "0 (упорный торец)",
  "Torque-turn controlled shoulder makeup": "Контроль свинчивания по крутящему моменту и углу поворота",
  "Direct wedge mating verification": "Контроль клинового сопряжения",
  "0 (Shoulder)": "0 (упорный торец)",
  "0 (Double shoulder)": "0 (двойной упорный уступ)",
  
  // --- Threads description translations ---
  "Standard API connection with external upset on tubing ends for standard oilfield completions.": "Стандартное резьбовое соединение API с высаженными концами труб для стандартных условий эксплуатации.",
  "API standard casing connection with buttress profile, offering high tensile strength.": "Стандартное резьбовое соединение API для обсадных труб с трапецеидальной резьбой (Buttress), обеспечивающее высокую прочность на растяжение.",
  "Standard Russian trapezoidal thread connection for casing strings.": "Стандартное российское трапецеидальное резьбовое соединение для обсадных колонн по ГОСТ 632.",
  "Russian premium casing connection with metal-to-metal seal and torque shoulder.": "Российское премиальное соединение для обсадных колонн с уплотнением металл-металл и упорным торцом.",
  "Premium gas-tight threaded connection for casing and tubing with metal-to-metal seal.": "Премиальное газогерметичное резьбовое соединение для обсадных и насосно-компрессорных труб с уплотнением металл-металл.",
  "Premium gas-tight connection with double torque shoulder and high compression rating.": "Премиальное газогерметичное соединение с двойным упорным уступом и высоким сопротивлением сжатию.",
  "Russian premium gas-tight connection family for tubing and casing with metal-to-metal seals.": "Семейство российских премиальных газогерметичных соединений для НКТ и обсадных труб с уплотнениями металл-металл.",
  "Chinese premium connection with high torque capacity and metal-to-metal seal.": "Китайское премиальное соединение с высокой крутящей способностью и уплотнением металл-металл.",
  "Next-generation premium connection featuring a unique threaded sleeve design and 100% burst/collapse envelope rating.": "Премиальное соединение нового поколения с уникальной конструкцией резьбовой муфты и 100% стойкостью к внутреннему и внешнему давлению.",
  "Premium integral connection utilizing a dovetail wedge thread profile that provides high torque capability without a torque shoulder.": "Премиальное интегральное соединение с клиновым профилем резьбы типа «ласточкин хвост», обеспечивающее высокую крутящую способность без упорного торца.",
  "Premium connection designed for high torque applications in drilling and casing strings.": "Премиальное соединение, разработанное для применения при высоких крутящих моментах в бурильных и обсадных колоннах.",
  "Dry premium connection requiring no thread compound (dope-free) for environmental safety.": "Премиальное соединение сухого свинчивания, не требующее резьбовой смазки (Dope-Free), для экологической безопасности.",
  "Premium casing/tubing thread designed with a unique pitch change to distribute load and reduce galling.": "Премиальная резьба для обсадных и насосно-компрессорных труб с переменным шагом для равномерного распределения нагрузки и снижения риска задиров.",
  "High-collapse premium casing thread optimized for thick-wall salt zone casings.": "Высокогерметичная премиальная резьба для обсадных труб, оптимизированная для толстостенных колонн в солевых интервалах.",
  "Standard flushing joint premium connection with gas-tight seal for slim-hole completions.": "Стандартное премиальное безмуфтовое соединение с газогерметичным уплотнением для заканчивания скважин малого диаметра.",
  "Two-step premium tubing connection with high tensile efficiency and gas-tight seal.": "Двухступенчатое премиальное соединение для НКТ с высокой эффективностью на растяжение и газогерметичным уплотнением.",
  "Standard two-step premium tubing connection with flush joint profile for clearance wells.": "Стандартное двухступенчатое премиальное соединение для НКТ с гладким (безмуфтовым) профилем для скважин с малым зазором.",
  "Drill pipe premium connection designed for extreme torsional loads in directional and ERD wells.": "Премиальное соединение для бурильных труб, разработанное для экстремальных крутящих моментов в наклонно-направленных скважинах и скважинах с большим отходом (ERD).",

  // --- Elastomers descriptions, advantages, limitations, and applications ---
  "Fluorocarbon elastomer with exceptional temperature and chemical resistance in sweet and mildly sour environments.": "Фторкаучуковый эластомер с исключительной температурной и химической стойкостью в слабокислых и бескислородных средах.",
  "Superb acid resistance": "Превосходная кислотостойкость",
  "Thermal stability up to 200°C": "Термическая стабильность до 200°C",
  "Excellent chemical stability": "Отличная химическая стойкость",
  "Rapidly degrades in steam, amines, and high concentration H2S (vulcanization reversal)": "Быстро разрушается под воздействием пара, аминов и высоких концентраций H₂S (обратная вулканизация)",
  "High temperature oil wells": "Высокотемпературные нефтяные скважины",
  "Acid stimulation wash packer seals": "Уплотнения пакеров при кислотных обработках",

  "Standard oilfield elastomer with excellent physical strength and wear resistance in low-temperature oil service.": "Стандартный промысловый эластомер с отличной механической прочностью и износостойкостью для низкотемпературных нефтяных сред.",
  "High wear resistance": "Высокая износостойкость",
  "Low cost": "Низкая стоимость",
  "Excellent mechanical properties and elasticity": "Отличные механические свойства и эластичность",
  "Poor resistance to ozone, polar solvents, H2S, and temperatures above 120°C": "Низкая стойкость к озону, полярным растворителям, H₂S и температурам выше 120°C",
  "Shallow oil production": "Неглубокие нефтяные скважины",
  "Standard surface equipment sealing": "Уплотнения стандартного наземного оборудования",

  "Hydrogenated nitrile elastomer showing high mechanical performance and better H2S resistance than NBR.": "Гидрированный бутадиен-нитрильный каучук, обладающий высокими механическими характеристиками и повышенной стойкостью к H₂S по сравнению с NBR.",
  "Excellent tensile strength": "Отличная прочность на растяжение",
  "High abrasion resistance": "Высокая стойкость к истиранию",
  "Good resistance to H2S": "Хорошая стойкость к сероводороду (H₂S)",
  "Moderate performance in hot steam and strong concentrated acids": "Умеренная стойкость в горячем паре и концентрированных кислотах",
  "Medium-temperature sour wells": "Скважины средней глубины с умеренным содержанием сероводорода",
  "Drilling BOP elements": "Элементы превенторов (ПВО) для бурения",

  "Ultimate performance perfluoroelastomer with near-complete chemical inertia, resisting severe sour service.": "Перфторкаучук с максимальными эксплуатационными характеристиками, практически полной химической инертностью и устойчивостью к жестким кислым средам.",
  "Extreme temperature resistance (300°C+)": "Экстремальная температурная стойкость (более 300°C)",
  "Resists practically all oilfield chemicals": "Устойчив практически ко всем промысловым химикатам",
  "Extremely expensive": "Чрезвычайно высокая стоимость",
  "Poor low-temperature elasticity": "Низкая эластичность при низких температурах",
  "Low mechanical tear resistance": "Низкое механическое сопротивление раздиру",
  "HPHT completions": "Заканчивание скважин HPHT (высокие давления и температуры)",
  "Deep sour gas injection wells": "Глубокие нагнетательные скважины кислого газа",
  "Chemical injection systems": "Системы дозирования химических реагентов",

  "Thermoplastic fluorpolymer with total chemical resistance. Used with elastomeric energizers.": "Фторопластовый термопласт с абсолютной химической стойкостью. Применяется с эластомерными активизаторами.",
  "Zero chemical degradation": "Нулевая химическая деструкция",
  "Extremely low coefficient of friction": "Крайне низкий коэффициент трения",
  "No explosive decompression": "Отсутствие риска взрывной декомпрессии (RGD)",
  "Subject to cold flow (creep) under compression": "Подвержен хладотекучести (ползучести) под сжимающей нагрузкой",
  "Zero elasticity (requires spring/rubber energizer)": "Нулевая эластичность (требует пружинного или резинового активизатора)",
  "Back-up rings for packer seals": "Опорные (защитные) кольца для уплотнений пакера",
  "HPHT dynamic seal assemblies": "Динамические уплотнительные узлы HPHT скважин",

  "Unique fluoroelastomer resistant to a broad range of harsh chemicals, specifically designed for steam, amines, and sour environments.": "Уникальный фторкаучук, стойкий к широкому спектру агрессивных химических сред, специально разработанный для пара, аминов и сероводорода.",
  "AFLAS is immune to amine-based corrosion inhibitors that destroy standard Viton (FKM)": "AFLAS невосприимчив к ингибиторам коррозии на основе аминов, разрушающим стандартный Viton (FKM)",
  "Exceptional steam service lifetime": "Исключительный срок службы в средах перегретого пара",
  "Avoid in sub-zero polar environments due to loss of elasticity below -10C": "Избегать использования в условиях отрицательных температур (теряет эластичность ниже -10°C)",
  "Avoid in presence of low-aniline point mineral oils": "Избегать контакта с минеральными маслами с низкой анилиновой точкой",
  "Packer seals in steam injection wells": "Уплотнения пакеров в паронагнетательных скважинах",
  "ESP cable protectors": "Протекторы кабеля УЭЦН",
  "Downhole chemical injection valves": "Скважинные клапаны дозирования химреагентов",

  "Standard oilfield elastomer designed for extreme hot water, steam, and polar chemical service, but completely incompatible with hydrocarbons.": "Стандартный промысловый эластомер для перегретой воды, пара и полярных сред, полностью несовместимый с углеводородами.",
  "Exceptional low-temperature elasticity down to -50C": "Исключительная низкотемпературная эластичность до -50°C",
  "Economic seal material for non-hydrocarbon geothermal systems": "Экономичный уплотнительный материал для безуглеводородных геотермальных систем",
  "Strictly avoid in any oil, gas, or hydrocarbon mud contact; even trace oil causes rapid seal failure": "Категорически избегать любого контакта с нефтью, газом или углеводородным раствором (даже следы вызывают быстрое разрушение)",
  "Steam stimulation well packer elements (hydrocarbon-free zones)": "Элементы пакеров скважин пароциклического воздействия (зоны без углеводородов)",
  "Subsurface safety valve hydraulic seals (water-based fluid)": "Гидравлические уплотнения скважинных клапанов-отсекателей (на водной основе)",

  "High-performance thermoplastic polymer offering exceptional mechanical strength, wear resistance, and chemical compatibility at high temperatures.": "Высокопрочный термопластичный полимер, обеспечивающий исключительную механическую прочность, износостойкость и химическую совместимость при высоких температурах.",
  "Combines metal-like mechanical strength with total chemical inertness up to 260C": "Сочает металлическую механическую прочность с полной химической инертностью до 260°C",
  "Standard anti-extrusion choice for HPHT O-ring seal packages": "Стандартный выбор защитных колец против экструзии для уплотнений HPHT",
  "Avoid where flexibility is required (rigid polymer, cannot function as a dynamic seal by itself)": "Избегать использования при необходимости высокой гибкости (жесткий полимер, не работает как динамическое уплотнение сам по себе)",
  "Extremely high raw material cost": "Чрезвычайно высокая стоимость исходного сырья",
  "Anti-extrusion backup rings for elastomer O-rings": "Защитные кольца против экструзии эластомерных колец",
  "Electrical connectors for logging-while-drilling (LWD) tools": "Электрические соединители для каротажных приборов (LWD) в процессе бурения",
  "Downhole ESP valve seats": "Седла клапанов скважинных насосов УЭЦН",

  "Thermoplastic elastomer with extreme mechanical strength, high wear and abrasion resistance.": "Термопластичный эластомер с экстремальной механической прочностью, высоким сопротивлением износу и истиранию.",
  "Extreme tensile and tear strength": "Экстремальная прочность на растяжение и раздир",
  "Excellent abrasion resistance in abrasive slurries": "Отличная износостойкость при перекачке абразивных суспензий",
  "No gas explosive decompression": "Отсутствие взрывной декомпрессии газа",
  "Hydrolyzes rapidly in hot water or steam (max temperature limit of 90°C)": "Быстро гидролизуется в горячей воде или паре (максимальная температура 90°C)",
  "Poor resistance to concentrated acids, aromatics, and H2S": "Низкая стойкость к концентрированным кислотам, ароматическим соединениям и H₂S",
  "Drill bit seal elements": "Уплотнения шарошечных буровых долот",
  "Rotating control device (RCD) seal elements": "Элементы уплотнений вращающихся превенторов (РКД)",
  "High wear slurry pump gaskets": "Прокладки шламовых насосов высокого износа",

  "Carboxylated nitrile elastomer offering supreme abrasion and tear resistance, for high mechanical load applications.": "Карбоксилатный бутадиен-нитрильный каучук, обеспечивающий превосходную стойкость к истиранию и раздиру для условий высоких механических нагрузок.",
  "Supreme resistance to mechanical tearing": "Превосходная стойкость к механическому раздиру",
  "Very high abrasion resistance": "Очень высокая стойкость к истиранию",
  "Good oil and water resistance": "Хорошая стойкость к воде и нефтепродуктам",
  "Poor elasticity compared to NBR": "Пониженная эластичность по сравнению с NBR",
  "High friction factor": "Высокий коэффициент трения",
  "Low resistance to polar solvents and ozone": "Низкая стойкость к полярным растворителям и озону",
  "Progressive cavity pump stators": "Статоры винтовых насосов",
  "ESP protector seals in high abrasive wells": "Уплотнения протекторов УЭЦН в высокоабразивных скважинах",
  "BOP ram packer packings": "Уплотнения плашек превенторов (ПВО)",

  // --- Elastomer tech parameter values ---
  "Medium to High (depending on compounding structure).": "От средней до высокой (в зависимости от рецептуры смеси).",
  "Poor.": "Низкая.",
  "Excellent (in specific HPHT compounds).": "Отличная (в специальных смесях для HPHT).",
  "Immune (no gas solubility).": "Иммунитет (газ не растворяется).",
  "Medium.": "Средняя.",
  "Excellent.": "Отличная.",
  "Poor. Suffers rapid chemical reverse vulcanization.": "Низкая. Подвержен быстрой химической реверсии вулканизации.",
  "Exceptional.": "Исключительная.",
  "Moderate.": "Умеренная.",
  "Very poor. Hydrolyzes rapidly in hot water or steam.": "Очень низкая. Быстро гидролизуется в горячей воде или паре.",
  "Poor. Suffers steam degradation above 100°C.": "Низкая. Подвержен паровой деструкции выше 100°C.",
  "Excellent with HCl stimulation fluids.": "Отличная для солянокислотных обработок (HCl).",
  "Exceptional (HCl, HF).": "Исключительная (к соляной HCl и плавиковой HF кислотам).",
  "Poor. Degrades in hydrochloric or organic stimulation acids.": "Низкая. Разрушается в соляной кислоте или органических кислотах.",
  "Moderate. Resists trace concentrations of acid wash.": "Умеренная. Выдерживает минимальные концентрации кислотных составов.",
  "Amine hardening, chemical degradation in steam/amines.": "Отверждение аминами, химическая деструкция в паре/аминах.",
  "Ozone cracking, heat embrittlement, sour gas swelling.": "Озоновое растрескивание, тепловое охрупчивание, набухание в сероводороде.",
  "Dynamic extrusion due to low mechanical tear strength, low temperature leakage.": "Динамическое выдавливание (экструзия) из-за низкой прочности на раздир, утечки при низких температурах.",
  "Cold flow (creep) deformation, lack of elastic memory.": "Деформация хладотекучести (ползучести), отсутствие эластичной памяти.",
  "Abrasion and thermal hardening.": "Истирание и термическое отверждение.",
  "Hydrolysis (reversion), chemical degradation by acids and H2S, thermal softening.": "Гидролиз (реверсия), химическая деструкция кислотами и H₂S, термическое размягчение.",
  "Thermal oxidation, cracking, wear in sour gas.": "Термическое окисление, растрескивание, износ в сероводороде.",
  "Aged storage up to 10 years in sealed bags away from ozone.": "Срок хранения до 10 лет в герметичных пакетах вдали от озона.",
  "Max 5 years shelf life. Keep out of daylight.": "Срок хранения не более 5 лет. Беречь от дневного света.",
  "Unlimited shelf life. Avoid compression.": "Неограниченный срок хранения. Избегать сжатия.",
  "Store dry. Shield from dust.": "Хранить в сухом месте. Защищать от пыли.",
  "Store in dry room.": "Хранить в сухом помещении.",
  "Store in cool, dark, dry environment. Avoid moisture.": "Хранить в прохладном, темном и сухом месте. Избегать влаги.",
  "Cool, dry space, away from UV and ozone.": "Прохладное, сухое место вдали от УФ-лучей и озона.",
  "Fluorocarbon elastomer with exceptional temperature and chemical resistance in sweet and mildly sour environments": "Фторкаучуковый эластомер с исключительной температурной и химической стойкостью в слабокислых и бескислородных средах",

  // --- New Steel Grades Translations ---
  "High-strength martensitic stainless steel alloyed with Nickel and Molybdenum for wet CO2 and mild H2S service.": "Высокопрочная мартенситная нержавеющая сталь с добавлением никеля и молибдена для работы во влажной среде CO₂ и умеренно кислых средах H₂S.",
  "Martensitic stainless steel (13% Cr, 4-6% Ni, 1-2% Mo, ultra-low Carbon)": "Мартенситная нержавеющая сталь (13% Cr, 4-6% Ni, 1-2% Mo, ультранизкое содержание углерода)",
  "Resistant to H2S under NACE MR0175 / ISO 15156 limits (pH > 4.5, mild H2S)": "Стойкость к сероводороду H₂S в пределах ограничений NACE MR0175 / ISO 15156 (при pH > 4.5, слабокислая среда)",
  "Thermally stable and highly resistant up to 180C (356F)": "Термически стабильна и обладает высокой стойкостью при температурах до 180°C (356°F)",
  "Outstanding resistance to wet CO2 and pitting corrosion. Far superior to standard 13Cr.": "Превосходная стойкость к влажной углекислотной коррозии и питтингу. Значительно превосходит стандартную сталь 13Cr.",
  "Vastly superior CO2 resistance compared to standard 13Cr": "Значительно превосходит стандартную 13Cr по стойкости к коррозии CO₂",
  "Higher yield strength limits allowing deeper completions": "Повышенные пределы текучести позволяют спускать компоновки на большие глубины",
  "Eliminates need for continuous chemical corrosion inhibition": "Исключает необходимость непрерывного дозирования ингибиторов коррозии",
  "Significantly higher cost than standard 13Cr": "Существенно более высокая стоимость по сравнению со стандартной сталью 13Cr",
  "Susceptible to cracking in high H2S concentrations with low pH": "Подвержен растрескиванию при высоких концентрациях H₂S в условиях низкого pH",
  "High-flow wet CO2 gas wells": "Высокодебитные газовые скважины с влажным CO₂",
  "Deepwater gas completions": "Заканчивание глубоководных газовых скважин",
  "Mildly sour reservoir environments": "Слабокислые пластовые среды",
  "Ensure pH and chloride limits are verified against ISO 15156-3 environmental limits before deployment.": "Перед использованием убедитесь, что значения pH и содержания хлоридов соответствуют экологическим лимитам стандарта ISO 15156-3.",
  "API 5CT high-strength carbon steel grade with strictly controlled chemistry and hardness for severe H2S sour service.": "Высокопрочный сорт углеродистой стали по API 5CT со строго контролируемым химическим составом и твердостью для жестких условий кислых сред H₂S.",
  "Chromium-molybdenum low-alloy steel, controlled hardness (Max 26 HRC)": "Хромомолибденовая низколегированная сталь, контролируемая твердость (макс. 26 HRC)",
  "Fully rated for severe H2S sour service environments under NACE MR0175 / ISO 15156 limits": "Полностью соответствует условиям эксплуатации в жестких средах H₂S в соответствии с ограничениями NACE MR0175 / ISO 15156",
  "Stable down to -29C, suitable for high-temperature wells up to 200C": "Стабильна при температурах до -29°C, подходит для высокотемпературных скважин до 200°C",
  "Excellent resistance to Sulfide Stress Cracking (SSC) under high tensile loads.": "Отличная стойкость к сульфидному растрескиванию под напряжением (РКН) при высоких растягивающих нагрузках.",
  "Highest strength API carbon steel grade rated for severe H2S service": "Наиболее прочная группа углеродистой стали API, предназначенная для эксплуатации в тяжелых средах H₂S",
  "Excellent fracture toughness and crack resistance": "Отличная вязкость разрушения и стойкость к образованию трещин",
  "Strict quality control ensures minimal hardness variations": "Строгий контроль качества обеспечивает минимальный разброс твердости",
  "High cost compared to L80 and C90": "Высокая стоимость по сравнению с L80 и C90",
  "Requires careful welding and handling procedures to avoid local hardening": "Требует осторожности при сварке и монтаже для избежания локальной закалки металла",
  "Deep high-pressure sour gas completions": "Глубокие заканчивания газовых скважин с АВПД и высоким содержанием сероводорода",
  "Critical well control casing strings": "Ответственные обсадные колонны контроля давления скважины",
  "Hardness must be verified across the body and joint to not exceed 26 HRC.": "Твердость тела трубы и замка должна быть проверена и не должна превышать 26 HRC.",
  "Highly alloyed austenitic stainless steel with outstanding resistance to acid stimulation, wet CO2, and severe H2S.": "Высоколегированная аустенитная нержавеющая сталь с исключительной стойкостью к обработкам кислотами, влажному CO₂ и жесткому сероводороду H₂S.",
  "High-alloy austenitic stainless steel (31% Ni, 27% Cr, 3.5% Mo, 1% Cu)": "Высоколегированная аустенитная нержавеющая сталь (31% Ni, 27% Cr, 3.5% Mo, 1% Cu)",
  "Outstanding resistance in severe sour environments (up to 100% H2S)": "Выдающаяся стойкость в тяжелых кислых средах (до 100% содержания H₂S)",
  "Exceptional mechanical and chemical stability up to 200C (392F)": "Исключительная механическая и химическая стабильность при температурах до 200°C (392°F)",
  "Excellent resistance to localized pitting, crevice corrosion, and chloride stress corrosion cracking.": "Отличная устойчивость к локальному питтингу, щелевой коррозии и хлоридному коррозионному растрескиванию под напряжением.",
  "Excellent cost-to-performance ratio compared to nickel-based alloys": "Отличное соотношение цены и эксплуатационных качеств по сравнению с никелевыми сплавами",
  "Immune to chloride-induced stress corrosion cracking": "Абсолютно устойчив к хлоридному коррозионному растрескиванию под напряжением",
  "Outstanding resistance in hydrochloric and hydrofluoric acid stimulations": "Исключительная стойкость к воздействию соляной и плавиковой кислот при ОПЗ",
  "High thermal expansion coefficient requires careful design considerations": "Высокий коэффициент теплового расширения требует тщательного проектирования обсадной колонны",
  "Requires specialized welding procedures": "Требует специальных технологий проведения сварочных работ",
  "Deep sour gas wells with high chloride content": "Глубокие газовые скважины с высоким содержанием сероводорода и хлоридов",
  "Corrosive geothermal completions": "Заканчивание геотермальных скважин с агрессивной средой",
  "Ensure compatibility with completion fluids (e.g. zinc bromides can cause stress corrosion under high temperatures).": "Убедитесь в совместимости со скважинными жидкостями заканчивания (например, бромид цинка при высоких температурах может вызвать коррозионное растрескивание).",
  "High-strength alpha-beta titanium alloy offering exceptional strength-to-weight ratio and superb corrosion resistance in geothermal steam.": "Высокопрочный альфа-бета титановый сплав с выдающимся соотношением прочности к весу и превосходной коррозионной стойкостью в геотермальном паре.",
  "Titanium alloy (6% Aluminum, 4% Vanadium, balance Titanium)": "Титановый сплав (6% алюминия, 4% ванадия, остальное — титан)",
  "Highly resistant to sour environments and wet acid gases up to high temperatures": "Высокая стойкость к кислым средам и влажным газам вплоть до высоких температур",
  "Retains structural and mechanical properties up to 350C (662F)": "Сохраняет конструкционные и механические свойства при температурах до 350°C (662°F)",
  "Virtually immune to pitting, crevice corrosion, and sweet/sour weight-loss corrosion.": "Практически полностью устойчив к питтингу, щелевой коррозии и общей потере веса от углекислотной/сероводородной коррозии.",
  "Deepwater risers": "Глубоководные буровые райзеры",
  "Geothermal liners": "Хвостовики геотермальных скважин",
  "Downhole logging tool housings": "Корпуса каротажных геофизических приборов",
  "Exceptional strength-to-weight ratio (45% lighter than steel)": "Исключительное соотношение прочности к весу (на 45% легче стали)",
  "Excellent flexibility and outstanding fatigue life in marine environments": "Отличная гибкость и выдающийся усталостный ресурс в морских условиях",
  "Total corrosion immunity in geothermal steam and wet chlorides": "Полная коррозионная стойкость в геотермальном паре и влажных хлоридах",
  "Extremely high raw material and fabrication cost": "Крайне высокая стоимость сырья и производства",
  "High galling tendency during makeup requiring special thread coatings": "Высокая склонность к задирам при свинчивании резьбы, требующая нанесения специальных покрытий",
  "Geothermal completions": "Заканчивание геотермальных скважин",
  "Ultra-deepwater offshore drilling risers": "Буровые райзеры для сверхглубоких вод",
  "Critical marine components": "Ответственные узлы морского оборудования",
  "Use specialized copper-free, non-metallic thread compounds to prevent electrochemical galvanic corrosion.": "Используйте специальные безмедные неметаллические резьбовые смазки для исключения электрохимической гальваниической коррозии.",

  // --- New Elastomers Translations ---
  "Specialized fluorinated silicone rubber offering outstanding low-temperature elasticity and fuel resistance, ideal for arctic surface equipment.": "Специализированный фторсиликоновый каучук, обеспечивающий выдающуюся низкотемпературную эластичность и топливостойкость, идеальный для арктического устьевого оборудования.",
  "Fluorinated silicone rubber": "Фторированный силиконовый каучук (FVMQ)",
  "Wellhead static seals": "Статические уплотнения устьевой арматуры",
  "Arctic fuel line gaskets": "Прокладки топливных линий для арктического применения",
  "Low-temperature sensor o-rings": "Уплотнительные кольца датчиков низких температур",
  "Exceptional low-temperature flexibility down to -60°C": "Исключительная гибкость при низких температурах до -60°C",
  "Good resistance to petroleum oils and fuels": "Хорошая стойкость к нефтяным маслам и топливу",
  "Excellent weather and ozone resistance": "Отличная стойкость к погодным условиям и озону",
  "Low. Susceptible to rapid gas decompression damage due to high gas permeability.": "Низкая. Чувствителен к повреждениям от взрывной декомпрессии из-за высокой газопроницаемости.",
  "Low. Not recommended for sour service completions.": "Низкая. Не рекомендуется для заканчивания кислых скважин.",
  "Poor. Suffers rapid hydrolysis in steam and hot water above 100°C.": "Низкая. Подвержен быстрому гидролизу в паре и горячей воде выше 100°C.",
  "Moderate. Poor resistance to strong acids.": "Умеренная. Низкая стойкость к сильным концентрированным кислотам.",
  "Physical tear, explosive decompression, ozone degradation.": "Механический раздир, взрывная декомпрессия, озоновое старение.",
  "Store in cool, dry place, strictly away from direct UV radiation.": "Хранить в прохладном, сухом месте, строго вдали от прямого УФ-излучения.",
  "Poor mechanical strength; avoid dynamic applications.": "Низкая механическая прочность; избегайте динамических уплотнений.",
  "Surface wellheads in arctic environments": "Наземная устьевая арматура в арктических климатических условиях",
  "Static electrical connector seals": "Уплотнения статических электрических разъемов",
  "Premium perfluoroelastomer featuring near-complete chemical inertness, excellent thermal stability, and superior explosive decompression resistance.": "Премиальный перфторкаучук, обладающий практически полной химической инертностью, отличной термической стабильностью и высочайшей стойкостью к взрывной декомпрессии.",
  "Perfluoroelastomer": "Перфторкаучук (FFKM)",
  "HPHT packers": "Пакеры для условий HPHT (высокого давления и температур)",
  "SFT valve seals": "Уплотнения клапанов SFT",
  "Chemical injection lines": "Линии нагнетания химреагентов",
  "Universal chemical resistance (near-complete inertness)": "Универсальная химическая стойкость (почти полная инертность)",
  "Thermal stability up to 325°C": "Термическая стабильность при температурах до 325°C",
  "Excellent. Outstanding performance in high-pressure rapid gas decompression environments.": "Отличная. Выдающиеся показатели при быстром падении давления газа высокого давления (RGD).",
  "Outstanding. Highly recommended for severe H2S completions.": "Выдающаяся. Настоятельно рекомендуется для заканчивания скважин с высоким содержанием сероводорода H₂S.",
  "Excellent. Thermally stable in steam up to 300°C.": "Отличная. Термически стабилен в паре при температурах до 300°C.",
  "Outstanding. Immune to acid stimulation fluids.": "Выдающаяся. Полностью инертен к кислотным составам при ОПЗ.",
  "Extrusion under high pressure without backup rings, poor low-temperature hardening.": "Выдавливание (экструзия) под высоким давлением без защитных колец, потеря эластичности при низких температурах.",
  "Standard elastomer storage guidelines apply. Clean, dark, dry conditions.": "Применяются стандартные правила хранения эластомеров: сухое, чистое, темное помещение.",
  "High cost, limited low-temperature elasticity.": "Высокая стоимость, ограниченная эластичность при низких температурах.",
  "Extreme HPHT sour gas completions": "Заканчивание экстремальных HPHT скважин в кислых средах",
  "Corrosive chemical injection systems": "Системы нагнетания агрессивных химреагентов",
  "Hydrogenated nitrile butadiene copolymer with high acrylonitrile content, offering maximum resistance to oil swelling and gas decompression.": "Гидрированный бутадиен-нитрильный каучук с высоким содержанием акрилонитрила (ACN), обеспечивающий максимальную стойкость к набуханию в масле и взрывной декомпрессии.",
  "Hydrogenated nitrile butadiene copolymer with high acrylonitrile content": "Гидрированный бутадиен-нитрильный сополимер с высоким содержанием акрилонитрила",
  "BOP seal elements": "Уплотнительные элементы превенторов (ПВО)",
  "ESP protectors": "Протекторы погружных насосов УЭЦН",
  "Downhole motor stators": "Статоры винтовых забойных двигателей",
  "Vastly superior resistance to explosive decompression (RGD)": "Значительно превосходит стандартный HNBR по стойкости к взрывной декомпрессии (RGD)",
  "Excellent resistance to petroleum oils and hot water": "Отличная стойкость к нефтяным маслам и горячей воде",
  "Outstanding. High ACN level provides density to resist explosive decompression.": "Выдающаяся. Высокое содержание акрилонитрила обеспечивает плотность для сопротивления взрывной декомпрессии.",
  "Excellent. Highly suitable for moderate H2S gas and oil completions.": "Отличная. Подходит для заканчивания скважин с умеренным содержанием сероводорода H₂S.",
  "Good. Suitable for hot water and steam up to 150°C.": "Хорошая. Подходит для горячей воды и пара до 150°C.",
  "Moderate. Good resistance to organic acids, poor to concentrated mineral acids.": "Умеренная. Хорошая стойкость к органическим кислотам, низкая — к концентрированным минеральным кислотам.",
  "Thermal aging, low-temperature cracking, ozone exposure.": "Термическое старение, растрескивание при низких температурах, разрушение озоном.",
  "Keep in airtight containers away from UV light.": "Хранить в герметичных контейнерах вдали от УФ-излучения.",
  "Do not expose to temperatures below -20°C.": "Не допускать использования при температурах ниже -20°C.",
  "High-pressure gas wells with rapid decompression risks": "Высоконапорные газовые скважины с риском взрывной декомпрессии",
  "Submersible pump seals": "Уплотнения погружных насосов",

  // --- Standards Mappings Specific lists ---
  "Premium connections": "Премиальные резьбовые соединения",
  "Thread couplings": "Резьбовые муфты",
  "Validates gas tightness under combined loads": "Подтверждает герметичность резьбы при комбинированных нагрузках",
  "Standardizes connection ratings": "Стандартизирует рейтинги соединений",
  "CAL IV requires extreme testing envelopes and thermal cycling": "CAL IV требует экстремальных диапазонов испытаний и термоциклирования",
  "HPHT completions": "Заканчивание скважин HPHT (высокое давление/температура)",
  "Gas storage wells": "Скважины ПХГ (подземных хранилищ газа)",
  
  "Prevents brittle sulfide stress cracking": "Предотвращает хрупкое сульфидное растрескивание под напряжением",
  "Defines clear operational pH-H2S zones": "Определяет четкие зоны pH-H2S для эксплуатации",
  "Restricts maximum allowable material hardness to 22 HRC (for steels)": "Ограничивает максимальную твердость материала до 22 HRC (для сталей)",
  "Sour oil and gas wells": "Нефтяные и газовые скважины с содержанием сероводорода (кислые)",
  "Sulfide stress corrosion mitigation": "Снижение риска сульфидного коррозионного растрескивания",
  
  "Production packers": "Эксплуатационные пакеры",
  "Production tubing strings": "Колонны эксплуатационных НКТ",
  "Subsurface safety valves": "Скважинные клапаны-отсекатели",
  "Packer mandrels": "Оправки пакеров",
  "CO2 production wells": "Добывающие скважины с высоким содержанием CO₂",
  "Water injection wells with dissolved CO2": "Нагнетательные скважины с растворенным CO₂",
  "Corrosive sweet gas wells": "Добывающие скважины со сладким газом повышенной коррозионной активности",
  "Retrievable plugs": "Извлекаемые пробки",
  "Bridge plugs": "Мостовые пробки",
  "Guarantees packer sealing integrity downhole": "Гарантирует герметичность пакера в скважине",
  "Standardizes validation grades globally": "Стандартизирует уровни валидации на международном уровне",
  "V0/V3 testing is extremely expensive and time-consuming": "Испытания по классам V0/V3 крайне дорогостоящие и длительные",
  "Zonal isolation design": "Проектирование зональной изоляции пластов",
  "Subsea completion wells": "Скважины с подводным заканчиванием",
  
  "O-rings": "Уплотнительные кольца круглого сечения",
  "Packer elements": "Пакерные элементы (уплотнители)",
  "Subsurface valve seals": "Уплотнения скважинных клапанов",
  "Ensures seal longevity in harsh chemical environments": "Обеспечивает долговечность уплотнения в агрессивных химических средах",
  "Prevents RGD explosive blowout failures": "Предотвращает разрушения от взрывной декомпрессии газа (RGD)",
  "Norsok M-710 autoclave testing does not simulate dynamic seal wear": "Автоклавные испытания Norsok M-710 не моделируют динамический износ",
  "High-pressure gas completions": "Заканчивание газовых скважин высокого давления",
  "Arctic and geothermal seals validation": "Аттестация уплотнений для арктических и геотермальных условий",
  
  "Drill pipe tool joints": "Замковые соединения бурильных труб",
  "HWDP": "Тяжелые бурильные трубы (ТБТ)",
  "Drill collars": "Утяжеленные бурильные трубы (УБТ)",
  "Reduces risk of drillstring twist-offs": "Снижает риск обрыва бурильной колонны",
  "Standardizes inspection criteria across operators": "Стандартизирует критерии инспекции среди операторов",
  "Different wear categorization between DS-1 and API": "Различия в классификации износа между DS-1 and API",
  "Drillstring maintenance program": "Программа обслуживания бурильной колонны",
  "Ultra-deep and horizontal drilling operations": "Сверхглубокое и горизонтальное бурение",
  
  "Martensitic stainless steel with 13% Chromium, providing excellent resistance to CO2 weight-loss corrosion.": "Мартенситная нержавеющая сталь с содержанием хрома 13%, обеспечивающая отличную устойчивость к углекислотной коррозии (CO₂).",
  "Eliminates the need for continuous downhole corrosion inhibitors in CO2 wells": "Исключает необходимость непрерывной закачки ингибиторов коррозии в скважинах с высоким содержанием CO₂",
  "High yield strength equivalent to L80": "Высокий предел текучести, эквивалентный стали класса прочности L80",
  "Extremely prone to galling during makeup (requires premium thread compounds and slow makeup speed)": "Высокая склонность к задирам при свинчивании (требуются специализированные резьбовые смазки премиум-класса и низкая скорость свинчивания)",
  "High cost compared to L80 carbon steel": "Высокая стоимость по сравнению с углеродистой сталью L80",
  "Chloride Stress Corrosion Cracking (Chloride SCC)": "Хлоридное коррозионное растрескивание под напряжением (Chloride SCC)",
  "Chloride Stress Corrosion Cracking": "Хлоридное коррозионное растрескивание под напряжением",

  // --- Steel Grades Table Translations ---
  "13Cr Martensitic Stainless Steel": "Мартенситная нержавеющая сталь 13Cr",
  "25Cr Super Duplex Steel": "Супердуплексная сталь 25Cr",
  "28Cr Austenitic Stainless Steel": "Аустенитная нержавеющая сталь 28Cr",
  "Alloy 28 / Sanicro 28": "Сплав Alloy 28 / Sanicro 28",
  "C110 Sour Service Steel": "Сталь C110 для кислых сред",
  "C90 Sour Service Steel": "Сталь C90 для кислых сред",
  "22Cr Duplex Stainless Steel": "Дуплексная нержавеющая сталь 22Cr",
  "Incoloy 825 (Nickel-Iron-Chromium CRA)": "Incoloy 825 (железоникелевый сплав CRA)",
  "Inconel 625 (Nickel CRA)": "Inconel 625 (никелевый сплав CRA)",
  "Inconel 718 (Nickel-Based CRA)": "Inconel 718 (никелевый сплав CRA)",
  "Inconel 725 (High-Strength CRA)": "Inconel 725 (высокопрочный никелевый сплав CRA)",
  "J55 Carbon Steel": "Углеродистая сталь J55",
  "K55 Carbon Steel": "Углеродистая сталь K55",
  "L80 Carbon Steel": "Углеродистая сталь L80",
  "L80 Type 1 Carbon Steel": "Углеродистая сталь L80 тип 1",
  "L80 13Cr Martensitic Steel": "Мартенситная сталь L80 13Cr",
  "Monel 400 (Nickel-Copper Alloy)": "Монель 400 (никель-медный сплав)",
  "N80 Type 1 Steel": "Сталь N80 тип 1",
  "N80Q Carbon Steel": "Углеродистая сталь N80Q",
  "P110 Carbon Steel": "Углеродистая сталь P110",
  "Q125 High-Strength Steel": "Высокопрочная сталь Q125",
  "Super 13Cr Steel (HP2-13Cr / HP13Cr)": "Сталь Super 13Cr (HP2-13Cr / HP13Cr)",
  "Super 13Cr (HP2-13Cr)": "Сталь Super 13Cr (HP2-13Cr)",
  "T95 Sour Service Steel": "Сталь T95 для кислых сред",
  "Titanium Grade 5 (Ti-6Al-4V)": "Титан Grade 5 (Ti-6Al-4V)",
  "VM125HC High-Collapse Steel": "Высокопрочная сталь с сопротивлением к смятию VM125HC",

  "Limited. Suitable for trace H2S only (partial pressure H2S < 0.1 psi / 1.5 kPa) depending on pH.": "Ограниченно. Подходит только для следовых концентраций H₂S (парциальное давление H₂S < 0,1 psi / 1,5 кПа) в зависимости от pH.",
  "Highly compatible (excellent resistance to SSC and SCC)": "Высокая совместимость (отличная стойкость к сульфидному растрескиванию и коррозионному растрескиванию под напряжением)",
  "Outstanding resistance in severe sour environments (up to 100% H2S)": "Исключительная стойкость в жестких кислых средах (до 100% H₂S)",
  "Fully rated for severe H2S sour service environments under NACE MR0175 / ISO 15156 limits": "Полное соответствие для эксплуатации в жестких средах H₂S в рамках ограничений NACE MR0175 / ISO 15156",
  "Fully suitable for severe sour service (100% H2S) with no limits under NACE MR0175 up to high temperatures.": "Полностью подходит для жестких кислых сред (100% H₂S) без ограничений по NACE MR0175 до высоких температур.",
  "Excellent, fully approved for severe sour service without H2S limit up to 232C": "Отличная стойкость, полностью одобрено для жестких кислых сред без ограничений по H₂S до 232°C",
  "Suitable for H2S service under NACE MR0175 / ISO 15156 limits": "Подходит для эксплуатации в средах H₂S в пределах ограничений NACE MR0175 / ISO 15156",
  "NOT suitable for H2S service (susceptible to rapid Sulfide Stress Cracking)": "НЕ подходит для сред H₂S (подвержен быстрому сульфидному растрескиванию под напряжением)",
  "Generally NOT suitable for sour service, though highly controlled chemistry Q125 can be used in limited mild sour conditions with operator approval": "Обычно НЕ подходит для кислых сред, хотя сталь Q125 с жестко контролируемым химическим составом может использоваться в ограниченных слабокислых условиях по согласованию с оператором",
  "Resistant to H2S under NACE MR0175 / ISO 15156 limits (pH > 4.5, mild H2S)": "Устойчив к H₂S в пределах ограничений NACE MR0175 / ISO 15156 (при pH > 4,5 и слабой концентрации H₂S)",
  "Intermediate. Suitable for H2S partial pressures up to 1.5 psi (10 kPa) depending on pH and temperature.": "Средняя стойкость. Подходит для парциального давления H₂S до 1,5 psi (10 кПа) в зависимости от pH и температуры.",
  "Highly resistant to sour environments and wet acid gases up to high temperatures": "Высокая стойкость к кислым средам и влажным кислым газам до высоких температур",

  "Deep sour gas wells with high chloride content": "Глубокие скважины с кислым газом и высоким содержанием хлоридов",
  "Deep high-pressure sour gas completions": "Заканчивание глубоких газовых скважин высокого давления с кислыми средами",
  "HPHT severe sour wells": "Глубокие скважины HPHT с жесткими кислыми средами",
  "Production and injection wells with mild H2S": "Добывающие и нагнетательные скважины со слабым содержанием H₂S",
  "Deep vertical wells": "Глубокие вертикальные скважины",
  "Deep gas wells": "Глубокие газовые скважины",
  "High-flow wet CO2 gas wells": "Высокодебитные газовые скважины с влажным CO₂",
  "Deep hot wells with CO2 and mild H2S": "Глубокие горячие скважины с CO₂ и слабым содержанием H₂S",
  "Geothermal completions": "Заканчивание геотермальных скважин",

  "110,000 - 125,000 psi (cold-worked)": "110 000 - 125 000 psi (холоднодеформированная)",
  "Min 110,000 psi (758 MPa)": "Мин. 110 000 psi (758 МПа)",
  "Min 120,000 psi (827 MPa)": "Мин. 120 000 psi (827 МПа)",
  
  "Subsurface safety valve springs and housings": "Пружины и корпуса скважинных клапанов-отсекателей",
  "HPHT packer components": "Компоненты пакеров для условий HPHT",
  "Logging tool housings": "Корпуса каротажных приборов",
  "Wellhead valve gates": "Шиберы задвижек устьевой арматуры"
};

/**
 * Translates English database and profile text to Russian.
 * 
 * @param {string} text - The input English string.
 * @param {string} lang - Selected language ('ru' or 'en').
 * @returns {string} Translated string or original text.
 */
export function translateDbText(text, lang) {
  const isDebug = typeof localStorage !== 'undefined' && localStorage.getItem('hadalbore_loc_debug_mode') === 'true';
  if (!text) return text;

  if (lang !== 'ru') {
    return isDebug ? `db🌐[${text}]` : text;
  }
  
  const trimmed = String(text).trim();
  const hasCyrillic = /[а-яА-ЯёЁ]/.test(trimmed);
  if (hasCyrillic) {
    return isDebug ? `db🌐[${trimmed}]` : trimmed;
  }

  if (DB_TRANSLATIONS[trimmed]) {
    return isDebug ? `db🌐[${DB_TRANSLATIONS[trimmed]}]` : DB_TRANSLATIONS[trimmed];
  }

  // Handle minor character variations (e.g. trailing dots, spaces)
  const normalized = trimmed.replace(/\.$/, '');
  if (DB_TRANSLATIONS[normalized]) {
    const res = DB_TRANSLATIONS[normalized] + (trimmed.endsWith('.') ? '.' : '');
    return isDebug ? `db🌐[${res}]` : res;
  }

  return isDebug ? `db⚠️[${text}]⚠️` : text;
}

export default { translateDbText };
