import fs from 'fs';
import path from 'path';

const DB_PATH = '/Users/niko/Documents/Личное/AI/Antigravity/OmniLab/src/data/mock-db.json';
const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf8'));

const newTubulars = [
  {
    "id": "casing_4500_l80",
    "type": "Tubular",
    "name": "4.500\" L80 Casing",
    "aliases": ["4-1/2 L80", "4.5 L80", "114мм L80", "114 L80", "ОК 114 L80"],
    "description": "API Specification 5CT grade L80 casing, commonly used for production casing strings in deep oil and gas wells.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -29, "max": 150, "unit": "C" },
    "pressure": { "min": 0, "max": 8430, "unit": "psi" },
    "chemicalComposition": ["Carbon Steel (C-Mn) Quenched & Tempered"],
    "chemicalCompatibility": ["Produced oil", "Fresh water", "Brines", "Moderate H2S"],
    "usedInEquipment": ["Production casing strings", "Intermediate casing strings"],
    "advantages": ["Good H2S cracking resistance", "Quenched & Tempered grain structure", "High yield strength constraint"],
    "limitations": ["Requires chemical inhibition in sweet CO2 wells with high water cut"],
    "applications": ["Sour service well completions", "Production casing in medium/deep wells"],
    "diagrams": ["makeup-loss"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 4.5,
    "weight": 13.5,
    "inner_dia": 3.92,
    "drift_id": 3.795,
    "grade": "L80",
    "tubular_type": "Casing",
    "burst": 8430,
    "collapse": 8070,
    "tensile": 315000,
    "confidenceLevel": "High"
  },
  {
    "id": "casing_7000_l80",
    "type": "Tubular",
    "name": "7.000\" L80 Casing",
    "aliases": ["7 L80", "7.0 L80", "178мм L80", "178 L80", "ОК 178 L80"],
    "description": "API Specification 5CT grade L80 casing for intermediate or production casing strings in deep reservoirs.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -29, "max": 150, "unit": "C" },
    "pressure": { "min": 0, "max": 7240, "unit": "psi" },
    "chemicalComposition": ["Carbon Steel (C-Mn) Quenched & Tempered"],
    "chemicalCompatibility": ["Produced oil", "Fresh water", "Brines", "Moderate H2S"],
    "usedInEquipment": ["Production casing strings", "Intermediate casing strings", "Downhole liners"],
    "advantages": ["Excellent sulfide stress cracking (SSC) resistance", "Highly ductile"],
    "limitations": ["Susceptible to general weight loss corrosion in wet CO2"],
    "applications": ["Intermediate casing for deviated wells", "Sour production casing strings"],
    "diagrams": ["makeup-loss"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 7.0,
    "weight": 26.0,
    "inner_dia": 6.276,
    "drift_id": 6.151,
    "grade": "L80",
    "tubular_type": "Casing",
    "burst": 7240,
    "collapse": 5410,
    "tensile": 604000,
    "confidenceLevel": "High"
  },
  {
    "id": "casing_9625_p110",
    "type": "Tubular",
    "name": "9.625\" P110 Casing",
    "aliases": ["9-5/8 P110", "9.625 P110", "244мм P110", "244 P110", "ОК 244 P110"],
    "description": "High-strength API Spec 5CT grade P110 casing for deep, high-pressure intermediate or production casing applications.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -20, "max": 180, "unit": "C" },
    "pressure": { "min": 0, "max": 9380, "unit": "psi" },
    "chemicalComposition": ["Alloy Steel (Cr-Mo) Quenched & Tempered"],
    "chemicalCompatibility": ["Standard drilling muds", "Brines", "Sweet gas"],
    "usedInEquipment": ["Intermediate casing strings", "Production casing strings"],
    "advantages": ["Very high tensile and yield strength", "High collapse resistance for salt zone squeezing"],
    "limitations": ["Not suitable for sour service (susceptible to SSC)"],
    "applications": ["High-pressure intermediate casing runs", "HPHT vertical and deviated wells"],
    "diagrams": ["makeup-loss"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 9.625,
    "weight": 47.0,
    "inner_dia": 8.681,
    "drift_id": 8.525,
    "grade": "P110",
    "tubular_type": "Casing",
    "burst": 9380,
    "collapse": 5300,
    "tensile": 1495000,
    "confidenceLevel": "High"
  },
  {
    "id": "casing_13375_n80",
    "type": "Tubular",
    "name": "13.375\" N80 Casing",
    "aliases": ["13-3/8 N80", "13.375 N80", "340мм N80", "340 N80", "ОК 340 N80"],
    "description": "Medium-strength API Spec 5CT grade N80 casing, typically used for surface or intermediate casing strings.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -20, "max": 120, "unit": "C" },
    "pressure": { "min": 0, "max": 3450, "unit": "psi" },
    "chemicalComposition": ["Medium carbon steel"],
    "chemicalCompatibility": ["Drilling muds", "Fresh water", "Cement"],
    "usedInEquipment": ["Surface casing string", "Intermediate casing string"],
    "advantages": ["Cost-effective intermediate strength option", "Good reliability in vertical sections"],
    "limitations": ["Highly susceptible to SSC in sour service", "Lower collapse rating"],
    "applications": ["Surface hole isolation", "Intermediate casing strings in shallow to medium depth wells"],
    "diagrams": ["makeup-loss"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 13.375,
    "weight": 68.0,
    "inner_dia": 12.415,
    "drift_id": 12.259,
    "grade": "N80",
    "tubular_type": "Casing",
    "burst": 3450,
    "collapse": 1950,
    "tensile": 1535000,
    "confidenceLevel": "High"
  },
  {
    "id": "tubing_2875_j55",
    "type": "Tubular",
    "name": "2.875\" J55 Tubing",
    "aliases": ["2-7/8 J55", "2.875 J55", "73мм J55", "73 J55", "НКТ 73 J55"],
    "description": "Standard API Specification 5CT grade J55 tubing for light-duty production and injection wells.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -20, "max": 120, "unit": "C" },
    "pressure": { "min": 0, "max": 7260, "unit": "psi" },
    "chemicalComposition": ["Carbon Steel (C-Mn)"],
    "chemicalCompatibility": ["Produced oil", "Fresh water", "Sweet gas"],
    "usedInEquipment": ["Standard completion strings", "Water injection strings"],
    "advantages": ["Highly economic", "Standard global availability"],
    "limitations": ["Vulnerable to sour corrosion", "Low tensile capacity"],
    "applications": ["Shallow vertical oil production wells", "Water injection wells"],
    "diagrams": ["tubing-connection"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 2.875,
    "weight": 6.5,
    "inner_dia": 2.441,
    "drift_id": 2.347,
    "grade": "J55",
    "tubular_type": "Tubing",
    "burst": 7260,
    "collapse": 7680,
    "tensile": 145000,
    "confidenceLevel": "High"
  },
  {
    "id": "tubing_3500_l80",
    "type": "Tubular",
    "name": "3.500\" L80 Tubing",
    "aliases": ["3-1/2 L80", "3.5 L80", "89мм L80", "89 L80", "НКТ 89 L80"],
    "description": "API Specification 5CT grade L80 production tubing for high-pressure or sour well completions.",
    "standards": ["API Spec 5CT", "ГОСТ 31446"],
    "temperature": { "min": -29, "max": 150, "unit": "C" },
    "pressure": { "min": 0, "max": 10160, "unit": "psi" },
    "chemicalComposition": ["Carbon Steel (C-Mn) Quenched & Tempered"],
    "chemicalCompatibility": ["Produced oil", "Brines", "Sour gas"],
    "usedInEquipment": ["Standard completion strings", "Gas lift strings", "ESP completions"],
    "advantages": ["Sour service NACE MR0175 compliant", "High mechanical envelope"],
    "limitations": ["Requires chemical inhibition for CO2 and high water cuts"],
    "applications": ["Sour gas and oil production wells", "HPHT completions"],
    "diagrams": ["tubing-connection"],
    "graphs": [],
    "sources": ["API Spec 5CT 10th Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2025",
    "od": 3.5,
    "weight": 9.3,
    "inner_dia": 2.992,
    "drift_id": 2.867,
    "grade": "L80",
    "tubular_type": "Tubing",
    "burst": 10160,
    "collapse": 10540,
    "tensile": 271000,
    "confidenceLevel": "High"
  },
  {
    "id": "drillpipe_5000_g105",
    "type": "Tubular",
    "name": "5.000\" G105 Drill Pipe",
    "aliases": ["5 G105", "5.0 G105", "127мм G105", "127 G105", "БТ 127 G105"],
    "description": "High-strength API Spec 5DP grade G105 drill pipe designed for heavy-duty drilling operations in medium to deep wells.",
    "standards": ["API Spec 5DP", "ISO 11961"],
    "temperature": { "min": -20, "max": 150, "unit": "C" },
    "pressure": { "min": 0, "max": 16500, "unit": "psi" },
    "chemicalComposition": ["Alloy Steel Quenched & Tempered"],
    "chemicalCompatibility": ["Drilling fluids", "Completion brines", "Fresh water"],
    "usedInEquipment": ["Drill string", "Workover strings"],
    "advantages": ["High torsional yield capacity", "Outstanding tensile load limit"],
    "limitations": ["Susceptible to Sulfide Stress Cracking in low-pH sour fluids"],
    "applications": ["Rotary drilling strings", "High-curvature deviated well drilling"],
    "diagrams": ["tubing-connection"],
    "graphs": [],
    "sources": ["API Spec 5DP 2nd Ed"],
    "lastUpdated": "2026-06",
    "revisionDate": "2020",
    "od": 5.0,
    "weight": 19.5,
    "inner_dia": 4.276,
    "drift_id": 4.151,
    "grade": "G105",
    "tubular_type": "Drill Pipe",
    "burst": 16500,
    "collapse": 15300,
    "tensile": 501000,
    "confidenceLevel": "High"
  }
];

newTubulars.forEach(t => {
  const exists = db.tubulars.some(x => x.id === t.id);
  if (!exists) {
    db.tubulars.push(t);
  }
});

fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf8');
console.log('Successfully expanded tubulars database with 7 new records.');
